### ISSUE TITLE
[ bug]ci v3.1.8 like use before

### ISSUE THREAD

**Issue by getpool** [bcit-ci/CodeIgniter#5469] opened 2018-04-11 12:26 UTC
system\database\DB_query_builder.php

find 
protected function _like(
				case 'before':
					$v = "%'{$v}'";
change
				case 'before':
					$v = "'%{$v}'";

**Comment by narfbg** [comment] 2018-04-13 10:52
Duplicate of #5462.

Please search for existing issues before posting.

**Closed by narfbg** 2018-04-13 10:52 UTC
