### ISSUE TITLE
update_batch issues

### ISSUE THREAD

**Issue by newdriv** [bcit-ci/CodeIgniter#4952] opened 2016-12-20 05:51 UTC
Not sure what is going on with you guys but some serious basic issues with 3.1.2.
Earlier I reported Image_lib issues
Now problems with update_batch
Same code in 2.2.4 works but not in 3.1.2 after update and again has similar footprints with syntax i.e the error is You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ... and so on. I am assuming again compiling the sql syntax issues
not sure if upgrading was any good thinking of reverting it back. Update should not least break the core functionality. Please don't go the apple or Mozilla route regarding updates
Please check

**Comment by narfbg** [comment] 2016-12-20 16:16
Duplicate of #4892.

Please use the search bar.
And don't assume we're going whatever route; bugs are bugs.

**Closed by narfbg** 2016-12-20 16:16 UTC

**Comment by newdriv** [comment] 2016-12-20 16:37
ohh my bad again placeholder search filters were not showing the results. 
The route is more versions and updates with some serious core functionality bugs. I would least assume Query Builder related bugs not to be there is any new releases.

**Comment by narfbg** [comment] 2016-12-24 13:56
I'd like to assume that there are no bugs ever, but that's not how it works.
