### ISSUE TITLE
Wrong IP address used in session manager

### ISSUE THREAD

**Issue by ukitconsultant** [bcit-ci/CodeIgniter#5287] opened 2017-10-05 09:44 UTC
The incorrect IP address is retrieved by the session manager when the site is behind Cloudflare or another similar tool. 

it doesn't use the http_x-forwarded-for server variable when it is available, instead always defaulting to the remote_addr server variable. This variable is used by various different services, and is a standardised response method. 

The remote_addr variable is automatically calculated by the server, but when the server is only receiving requests from a third party rather than directly from the browser (as this is what Cloudflare does!) then the remote_addr variable is not correctly able to distinguish one user from another based solely on their ip addresses, meaning 1000 sessions may all appear to come from the same IP address but belong to different users, which would get very confusing very quickly.

My recommendation would be to add a simple if statement anywhere the IP address is used to check for the existence of the http_x-fowarded-for variable and then use it if it exists, or remote_addr if it doesn't. 

There may be some services which this doesn't work for.

**Comment by narfbg** [comment] 2017-10-05 10:01
Duplicate of #4003.

**Closed by narfbg** 2017-10-05 10:01 UTC
