### ISSUE TITLE
_ci_prepare_view_vars does not prepare object because of mistake

### ISSUE THREAD

**Issue by frankenstein-uk** [bcit-ci/CodeIgniter#5005] opened 2017-02-03 13:36 UTC
$object variable does not exist and needs to be changed to $vars instead.

system/core/Loader.php

```
protected function _ci_prepare_view_vars($vars)
    {
        if ( ! is_array($vars))
        {
            $vars = is_object($vars)
                ? get_object_vars($object)
                : array();
        }

        foreach (array_keys($vars) as $key)
        {
            if (strncmp($key, '_ci_', 4) === 0)
            {
                unset($vars[$key]);
            }
        }

        return $vars;
    }
```

**Comment by narfbg** [comment] 2017-02-03 13:43
Duplicate of #4975.

**Closed by narfbg** 2017-02-03 13:43 UTC
