### ISSUE TITLE
DKIM Support on Codeigniter

### ISSUE THREAD

**Issue by isantolin** [bcit-ci/CodeIgniter#3626] opened 2015-02-25 14:50 UTC
"email" Library cant support DKIM mail signage

**Comment by aanbar** [comment] 2015-03-02 11:21
This should be done at the server level, not in a script/framework.

**Comment by isantolin** [comment] 2015-03-02 11:47
@aanbar This can be performed by PHP too... PHPMailer has support

https://stackoverflow.com/questions/24463425/send-mail-in-phpmailer-using-dkim-keys

**Comment by avenirer** [comment] 2015-03-02 12:23
Then use PHPMailer. That's the beauty of CodeIgniter...

**Comment by aanbar** [comment] 2015-03-05 11:05
@isantolin I am not saying it's a bad feature, What I am saying it's better to have it setup from within the server & have all emails signed by default.

Since you brought up PHPMailer, Here's a link from the creator of PHPMailer suggesting the same thing I am talking about: http://dkim.worxware.com/

Either way (Domain Wide OR Scripting) you'd have to create a DNS record to announce your public key so it's not just about CodeIgniter implementing this.

**Comment by Kaabi** [comment] 2015-08-12 07:15
@aanbar @isantolin honestly CI email library is very basic or could say is vintage library, for me I been using swiftmailer for 2 years which provide me all I need, I believe adding DKIM to current CI email library wont make the library anyway better they are tenths of things need to be added before DKIM.

so why CI just dont simply drop current email library and be based on swiftmailer instead like many php framework outthere does this.

**Comment by isantolin** [comment] 2017-02-17 16:03
@Kaabi @aanbar Is not a good idea drop a email library, because the crescent complexity of the good practices to send emails correctly, and its a frameworks DUTY, provide an Abstraction layer, full compatible with multiple systems and servers, to do that job

**Comment by Quix0r** [comment] 2017-06-22 07:49
@isantolin agreed, keep good libraries, drop bad ones (unmaintained, bad encapsulation, mostly bad code style, ...). Better is to then add something like a facade to hideaway the complexibility of such libs and provide an easy `interface` to it which everyone can remember.

**Comment by bscottdennis73** [comment] 2019-01-05 02:36
What bothers me about so many answers regarding CI issues is the fact that many of them recommend to import yet another file or package to get the functionality that should already exist. It seems a LOT of answers I see regarding Codeigniter involve "use another tool." My question is simple, why use CI to begin with when the answer to issues always seems to be to use another package or tool? What is the balance between a lightweight framework and one that continues to provide basic functionality involving best practices? If CI keeps deprecating features because they don't want to maintain best practices, eventually the framework isn't work the hassle.

**Comment by gxgpet** [comment] 2019-01-05 08:49
Would a PR be accepted with the DKIM implementation on Email lib?

**Comment by narfbg** [comment] 2019-01-06 21:01
> If CI keeps deprecating features because they don't want to maintain best practices, eventually the framework isn't work the hassle.

@bscottdennis73 I challenge you to point at a feature that we've deprecated because we don't want to support best practices.

@gxgpet What kind of a question is that? If the issue is still open, then of course PRs are welcome.

**Comment by narfbg** [comment] 2022-01-08 21:03
Closing as yet another "please add this" kind of issue. Pull requests are of course welcome.

**Closed by narfbg** 2022-01-08 21:03 UTC
Labels: Feature Request, Can of worms
