### ISSUE TITLE
Setting session using ajax not working

### ISSUE THREAD

**Issue by cretupaul** [bcit-ci/CodeIgniter#4996] opened 2017-01-25 19:25 UTC
Hi! I just try to set some session variable using ajax code, but from what i`ve discovered the data i set are not keept on the next screen refresh. Do you have any idea how to solve this. I`m pretty sure it is a codeigniter session management bug.

**Comment by narfbg** [comment] 2017-01-25 19:29
Duplicate of #4995.

Please stick to my advice about posting on the [forums](https://forum.codeigniter.com/) instead. Just saying the word "bug" doesn't change a thing.

**Closed by narfbg** 2017-01-25 19:29 UTC
Labels: Duplicate
