### ISSUE TITLE
Session.php has problem with this 

### ISSUE THREAD

**Issue by usback** [bcit-ci/CodeIgniter#6082] opened 2022-01-06 23:35 UTC
config.php has $config['cookie_httponly'] = true;
but error message 

```
Severity: Warning

Message: Undefined array key "cookie_httponly"

Filename: Session/Session.php

Line Number: 333

Backtrace:

File: /Users/unseobback/public_html/thewealthpointga/html/app/core/MY_Controller.php
Line: 17
Function: __construct

File: /Users/unseobback/public_html/thewealthpointga/html/app/controllers/Pages.php
Line: 16
Function: __construct

File: /Users/unseobback/public_html/thewealthpointga/html/index.php
Line: 335
Function: require_once


```

**Comment by usback** [comment] 2022-01-07 00:32
i found problem with 

that has problem this code 
```
	if (is_php('5.4'))
		{
			session_set_save_handler($class, TRUE);
		}
		else
		{
			session_set_save_handler(
				array($class, 'open'),
				array($class, 'close'),
				array($class, 'read'),
				array($class, 'write'),
				array($class, 'destroy'),
				array($class, 'gc')
			);

			register_shutdown_function('session_write_close');
		}
```

```
if (PHP_VERSION_ID >= 80100)
{
	session_set_save_handler(
		array($class, 'open'),
		array($class, 'close'),
		array($class, 'read'),
		array($class, 'write'),
		array($class, 'destroy'),
		array($class, 'gc')
	);
} 
else 
{
	session_set_save_handler($class, TRUE);
}
```

**Comment by narfbg** [comment] 2022-01-07 11:09
I'm marking this as a duplicate of #6083 (just fixed), as it appears to be the exact same issue. Please don't submit multiple issues for the same problem in the future.
However, it also appears that you're using custom code here. Please just pull the latest changes from 3.1-stable and do tell if you find any problems with that.

**Closed by narfbg** 2022-01-07 11:09 UTC
Labels: Duplicate
