### ISSUE TITLE
[3.1.3] core/Loader expects parameters

### ISSUE THREAD

**Issue by MathieuNls** [bcit-ci/CodeIgniter#4983] opened 2017-01-13 22:00 UTC
Hi,

I recently updated to CI 3.1.3 and I have the following errors coming up on my prod server:

```
> Severity: Warning --> get_object_vars() expects parameter 1 to be object, null given /app/system/core/Loader.php 1381
> Severity: Warning --> array_keys() expects parameter 1 to be array, null given /app/system/core/Loader.php 1385
> Severity: Warning --> Invalid argument supplied for foreach() /app/system/core/Loader.php 1385
> Severity: Warning --> get_object_vars() expects parameter 1 to be object, null given /app/system/core/Loader.php 1381
> Severity: Warning --> array_keys() expects parameter 1 to be array, null given /app/system/core/Loader.php 1385
> Severity: Warning --> Invalid argument supplied for foreach() /app/system/core/Loader.php 1385
> Severity: Warning --> get_object_vars() expects parameter 1 to be object, null given /app/system/core/Loader.php 1381
> Severity: Warning --> array_keys() expects parameter 1 to be array, null given /app/system/core/Loader.php 1385
> Severity: Warning --> Invalid argument supplied for foreach() /app/system/core/Loader.php 1385
> Severity: Warning --> get_object_vars() expects parameter 1 to be object, null given /app/system/core/Loader.php 1381
> Severity: Warning --> array_keys() expects parameter 1 to be array, null given /app/system/core/Loader.php 1385
> Severity: Warning --> Invalid argument supplied for foreach() /app/system/core/Loader.php 1385
```

Is this something known ? 

Thanks,
M.

**Comment by narfbg** [comment] 2017-01-13 22:05
Yes it is. Using the search bar would've taken you less time to find that out.

Duplicate of #4975.

**Closed by narfbg** 2017-01-13 22:05 UTC
