### ISSUE TITLE
User Guide Removing the Index.php Codeblock not rendering correctly.

### ISSUE THREAD

**Issue by jonhurlock** [bcit-ci/CodeIgniter#5374] opened 2018-01-04 00:14 UTC
In the User Guide under General, URLs the <b>Removing the index.php file</b> section found [here](https://www.codeigniter.com/user_guide/general/urls.html#removing-the-index-php-file) has a codeblock which is incorrectly rendered. 

Instead of reading as:

> If your Apache server has mod_rewrite enabled, you can easily remove this file by using a .htaccess file with some simple rules. Here is an example of such a file, using the “negative” method in which everything is redirected except the specified items:

```RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]
```
> In the above example, any HTTP request other than those for existing directories and existing files is treated as a request for your index.php file.

It instead reads as:

> If your Apache server has mod_rewrite enabled, you can easily remove this file by using a .htaccess file with some simple rules. Here is an example of such a file, using the “negative” method in which everything is redirected except the specified items:
`.. code-block:: console`
> > RewriteEngine On RewriteCond %{REQUEST_FILENAME} !-f RewriteCond %{REQUEST_FILENAME} !-d RewriteRule ^(.*)$ index.php/$1 [L]

> In the above example, any HTTP request other than those for existing directories and existing files is treated as a request for your index.php file.

I have placed a comment [here](https://github.com/bcit-ci/CodeIgniter/commit/ea21f113733e914d5d0c950d5bfb5c5624368407#commitcomment-26627281) on the original commit, which contains more details.

**Comment by jim-parry** [comment] 2018-01-04 00:20
I replied to your comment on the commit, pointing out that this *has* been fixed in the develop branch, and that the update will be part of the next CodeIgniter 3 release.

**Closed by jim-parry** 2018-01-04 00:20 UTC

**Comment by narfbg** [comment] 2018-01-04 08:07
Duplicate of #5283.
