### ISSUE TITLE
Double spacing in query where

### ISSUE THREAD

**Issue by asrul10** [bcit-ci/CodeIgniter#4237] opened 2015-11-12 03:52 UTC
Get from text
```
sales%20and%20marketing
```

and here is my code
```php
$url = "sales%20and%20marketing";
$category_decode = rawurldecode($url);
$filter = [
    'category' => $category_decode
];
```
if i echo it, it prints single spacing in query and become double space between 'and' and 'marketing' 

Here is my result of query in profiler
![scr profilert](http://ultraimg.com/images/where.jpg)

**Comment by narfbg** [comment] 2015-11-12 17:21
Duplicate of #4093.

**Closed by narfbg** 2015-11-12 17:21 UTC
