### ISSUE TITLE
_trans_status set outside a transaction

### ISSUE THREAD

**Issue by keynote** [bcit-ci/CodeIgniter#4026] opened 2015-08-04 21:23 UTC
If any query fails it sets _trans_status to FALSE. This causes any subsequent transaction (using trans_begin() or trans_start()) to fail as _trans_status is only reset during trans_complete(). 
It is possible to get a query failure, fix the issue and then attempt a transaction. The way the code works not the transaction will always fail even though all the queries within the transaction were successful. Shouldn't _trans_status be set to true during trans_begin when the 'START TRANSACTION' is done?

**Comment by jklovanc** [comment] 2015-08-04 23:45
On looking further the issue is bigger than I thought. The documentation has the following description for "strict mode";
"When strict mode is enabled, if you are running multiple groups of transactions, if one group fails all groups will be rolled back."
That is not true as transaction will be committed when level 0 of the transaction is reached.  As the code stands now the a query  failure in or out of a transaction will cause all future transaction to fail. A query failure will have no effect on and transaction that has been committed. 

Query faulure only effect previous queries is the transactions have been nested. Take a look at the following;
$this->db->trans_start();
//first queries
$this->db->trans_complete();
$this->db->trans_start();
//second queries
$this->db->trans_complete();
$this->db->trans_start();
//third queries
$this->db->trans_complete();
If the first queries complete it will be committed at the first trans_complete(). If the second queries do not complete the first transaction can not be rolled back as it has already been committed. The third  queries will roll back only in "strict mode".

Look at a nested query;
$this->db->trans_start();
    //some transaction
   $this->db->trans_start();
    //inside transaction
    $this->db->trans_complete();
    //last queries
$this->db->trans_complete();
In this case the commit only happens on the outside trans_complete(). Therefore all previous queries, after the first trans_start(), are rolled back. The trans_strict flag is meaningless as it only effects resetting on the outside trans_complete().

The issue comes in choosing where to reset the _trans_status flag. Currently it is set in trans_complete(). The problem with it being there is that queries before the transaction can set that flag to false and the transaction will fail.

I think it should be done in trans begin and the following line should be changed;
$this->_trans_failure = ($test_mode === TRUE) ? TRUE : FALSE;
Should be ;
if ($this->trans_strict === FALSE)
{
   $this->_trans_status = ($test_mode === TRUE) ? FALSE : TRUE ;
}
This resets the _trans_status flag on the outermost transaction with strict mode off and makes test_mode work. Currently test mode does not work as _trans_failure in not accessed anywhere. In the event that "strict mode" is on subsequent transactions will fail if any query fails. Right now any transaction fails if any previous query fails reguardless of "strict mode".

**Comment by keynote** [comment] 2015-08-05 00:49
Joe

You’re gonna have to explain this one to me

M

From: jklovanc
Reply-To: bcit-ci/CodeIgniter
Date: Tuesday, August 4, 2015 at 4:46 PM
To: bcit-ci/CodeIgniter
Cc: Podium 1
Subject: Re: [CodeIgniter] _trans_status set outside a transaction (#4026)


On looking further the issue is bigger than I thought. The documentation has the following description for "strict mode";
"When strict mode is enabled, if you are running multiple groups of transactions, if one group fails all groups will be rolled back."
That is not true as transaction will be committed when level 0 of the transaction is reached. As the code stands now the a query failure in or out of a transaction will cause all future transaction to fail. A query failure will have no effect on and transaction that has been committed.

Query faulure only effect previous queries is the transactions have been nested. Take a look at the following;
$this->db->trans_start();
//first queries
$this->db->trans_complete();
$this->db->trans_start();
//second queries
$this->db->trans_complete();
$this->db->trans_start();
//third queries
$this->db->trans_complete();
If the first queries complete it will be committed at the first trans_complete(). If the second queries do not complete the first transaction can not be rolled back as it has already been committed. The third queries will roll back only in "strict mode".

Look at a nested query;
$this->db->trans_start();
//some transaction
$this->db->trans_start();
//inside transaction
$this->db->trans_complete();
//last queries
$this->db->trans_complete();
In this case the commit only happens on the outside trans_complete(). Therefore all previous queries, after the first trans_start(), are rolled back. The trans_strict flag is meaningless as it only effects resetting on the outside trans_complete().

The issue comes in choosing where to reset the _trans_status flag. Currently it is set in trans_complete(). The problem with it being there is that queries before the transaction can set that flag to false and the transaction will fail.

I think it should be done in trans begin and the following line should be changed;
$this->_trans_failure = ($test_mode === TRUE) ? TRUE : FALSE;
Should be ;
if ($this->trans_strict === FALSE)
{
$this->_trans_status = ($test_mode === TRUE) ? FALSE : TRUE ;
}
This resets the _trans_status flag on the outermost transaction with strict mode off and makes test_mode work. Currently test mode does not work as _trans_failure in not accessed anywhere. In the event that "strict mode" is on subsequent transactions will fail if any query fails. Right now any transaction fails if any previous query fails reguardless of "strict mode".

**Comment by jklovanc** [comment] 2015-08-05 00:52
What is unclear?

**Closed** 2015-08-05 11:32 UTC

**Comment by narfbg** [comment] 2015-08-05 11:35
@jklovanc I got some clues from what you wrote, but the sheer size of your comment and it going back and forth between different issues does make it unclear.

The original issue reported by @keynote is fixed with the above commit. Please open a new one for what else you see as problematic, and possibly try to format it better. :)

**Comment by jklovanc** [comment] 2015-08-05 17:33
I am actually both people that submitted. The code change I submitted needs to be done in every driver and I do not have the time or inclination to fix your code. I tried to re-submit but the system blanked my input half way through editing. It goes back and forth a bit because there are two issues that are intertwined.  Maybe this will be a better explanation.
# First transaction after a failed query always fails.
All drivers use  _trans_status to track is a query has failed. It uses true on no failure and false on failure. That variable is set in three places;
1. True as a default on initialization.
2. False if a query fails.
3. True in trans_complete() if "strict mode" is of and the transaction is at nesting level 1. This is done after the rollback is done.
Take a look at the following scenario.
1. The class is initialized. This will set _trans_status to true.
2. A query fails. This will set _trans_status to false
3. A transaction is started. No change to _trans_status. It is still false.
4. Queries complete correctly.  No change to _trans_status. It is still false.
5. Trans_complete() is run.
  * Since _trans_status is false trans_rollback() will be run and all queries will be ignored.
  * If trans_strict is false, _trans_status is set to true.

As you can see the query ran before transaction will cause the transaction to rollback even though no queries failed in the transaction. This happens not matter what "strict mode" is set to.

Another issue I found was that there is a variable _trans_failure that is set in trans_start() but never used.
# Solution
The following changes need to be made to all the drivers as the problem exists in every driver.
1. The code to update _trans_status in trans_complete() needs to be removed.
2. The following changes need to be made to trans_start();
  * remove the following line.
>$this->_trans_failure = ($test_mode === TRUE) ? TRUE : FALSE;

 * replace with the following code;

> if ($this->trans_strict === FALSE)
> {
>    $this->_trans_status = ($test_mode === TRUE) ? FALSE : TRUE ;
> }

I honestly do not understand how your forking gets code back into the main repository.

**Comment by narfbg** [comment] 2015-08-06 12:55
Forking our repository provides you with the necessary commit privileges to make your changes (because the fork is in fact your repository).

After you've made those changes, all you need to do is to create a "Pull Request" (you'll have a button for that), which is basically the same as telling us this "I've made some changes that I want you to have, you can get them from repository X, branch Y." The difference being that we don't have to do that manually and it is easier to look at the diff, comment back and forth with you on it, automate testing, etc.
The [GitHub Help](https://help.github.com/) pages should be helpful if you can't quite understand it yet.

I'll continue the rest of the conversation in #4032 once I go through all the details and relevant pieces of code. :)
