### ISSUE TITLE
$this->input->set_cookie() must has $expire parameter

### ISSUE THREAD

**Issue by webqcc** [bcit-ci/CodeIgniter#5027] opened 2017-02-20 08:05 UTC
f ( ! is_numeric($expire))
{
	$expire = time() - 86500;
}
else
{
	$expire = ($expire > 0) ? time() + $expire : 0;
}

在使用$this->input->set_cookie($name, $value = '', $expire = '', $domain = '', $path = '/', $prefix = '', $secure = FALSE, $httponly = FALSE)中如果没有传递 $expire，那么最后 $expire就是一个time-的值，这个方法最后是调用php的setcookie()方法，对于$expire参数可以为time()+或者为0为空均可，但是time()-就不能正确设置cookie

**Comment by narfbg** [comment] 2017-02-20 08:08
Possible duplicate of #4904.

But regardless of that - this is an English-only territory.

**Closed by narfbg** 2017-02-20 08:08 UTC
