### ISSUE TITLE
[Bug] CI_Input get_request_header always returning null

### ISSUE THREAD

**Issue by neurolab** [bcit-ci/CodeIgniter#4104] opened 2015-09-09 15:12 UTC
[Line 806 of the Input.php file of CodeIgniter v3.0.1](https://github.com/bcit-ci/CodeIgniter/blob/3.0.1/system/core/Input.php#L806)

The line checks if `$this->headers` is empty : if not empty, it calls `$this->request_headers()`.
It misses a negation on the emptiness check, you want to fill the `$this->header` array if it is empty, so the line should be : 
```php
! empty($this->headers) OR $this->request_headers();
```

The result of this bug is that, when calling `get_request_header()` without calling `request_headers()` beforehand, the function will always return null because the headers array of the class is never filled.

**Comment by narfbg** [comment] 2015-09-09 15:27
Yet another duplicate of #4056 ... please use the search bar people.

**Closed by narfbg** 2015-09-09 15:27 UTC
