### ISSUE TITLE
Possible leaking on view load parameters?

### ISSUE THREAD

**Issue by Nom4d3** [bcit-ci/CodeIgniter#3928] opened 2015-06-24 12:58 UTC
Is this the correct behavior or it's a bug? Shouldn't the parameters be reset each time you load a view? Here is an example:

Controller Test.php
```php
<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Test extends CI_Controller {

   public function __construct()
   {
      parent::__construct();
   }

   public function index() {
      $data = array(
         array('a' => 'a', 'b' => 'b', 'c' => 'c'),
         array('a' => 'X')
      );

      echo "<pre>";
      print_r($data);

      foreach($data as $d) {
         $this->load->view('test', $d);
      }
   }
}
```

View test.php
```php
<?php
echo $a."<br>";
echo $b."<br>";
echo $c."<br>";
echo "---";
```

Output
```html

<pre>Array
(
    [0] => Array
        (
            [a] => a
            [b] => b
            [c] => c
        )

    [1] => Array
        (
            [a] => X
        )

)
a<br>b<br>c<br>---X<br>b<br>c<br>---
```

Wasn't b and c supposed to be empty on the second turn?

**Comment by narfbg** [comment] 2015-06-24 13:11
Duplicate of #514.

**Closed by narfbg** 2015-06-24 13:11 UTC
