### ISSUE TITLE
How to use memcached, redis other functions?

### ISSUE THREAD

**Issue by kekeones** [bcit-ci/CodeIgniter#4007] opened 2015-07-28 14:13 UTC
For example, I want to use the hset function redis ?
Whether to allow adding a magic method (__call) to call other functions？

**Comment by narfbg** [comment] 2015-07-28 14:19
Duplicate of #3943 ... which in turn is also not a valid feature request or bug report. You can read why in there, but please ask your questions on the [forums](http://forum.codeigniter.com/) instead.

**Closed by narfbg** 2015-07-28 14:19 UTC
Labels: Duplicate
