### ISSUE TITLE
Unable to inherit from MY_Model inherited Model

### ISSUE THREAD

**Issue by axelvaindal** [bcit-ci/CodeIgniter#4198] opened 2015-10-29 08:59 UTC
Greetings,
I am currently working on a small app, trying to organize it, and it appears something really weird is that I cannot inherit from a model which inherit itself from MY_Model

I have got this code in core/MY_Model.php:
```
class My_Model extends CI_Model
{
   // Definition of generic static methods such as all(), byId(), ...
}
```
This works fine, and I can inherit once from this Model with no issue. Eg, this code is actually working correctly : 
```
class Media extends My_Model
{
 // Definition of generic static methods for Media
}
```
But when I try to create a model inherited from the Media one, Code Igniter generate a "Unable to locate the specified file : Session.php'.
Eg, this code however, doesn't work, at least on my environment : 

```
class Image extends Media
{
// Definition of specific methods for Image
}
// In any controller, doing this generate the error :
$this->load->model('Image'); // Specified error.
```

Don't know if it's actually a bug, but I haven't found any documentation about this in CodeIgniter user's guide or on stackoverflow, so I chose to post it here, I hope this isn't an problem, just wanted to report it.
I know the Session bug has been reported before, but about nested controllers for example, or bad migration from 2.0 to 3.0 (library load instead of driver loading).

For now on, I just cp my code into which was into Media to all other previous inheritance, but I guess this is not a clean way to do, so if anyone has any solution about this weird inheritance issue, I would be very grateful.

Sincerely yours,
@axelvaindal

**Comment by narfbg** [comment] 2015-10-29 09:32
If you're getting that error, it means that you haven't properly followed the upgrade instructions and you still have the CI2 Session library. This particular error message isn't dependant on any conditions, it's always the same thing.

**Comment by narfbg** [comment] 2015-10-29 09:32
Duplicate of #3480.

**Closed by narfbg** 2015-10-29 09:32 UTC

**Comment by axelvaindal** [comment] 2015-10-29 09:40
Actually, I downloaded the actual source code from Code Igniter v3.0.2 two weeks ago.
So don't understand how this could be upgrading instructions problem.

Will have further look at my config.php and autoload.php file to see if correct.

Thanks,

**Comment by narfbg** [comment] 2015-10-29 09:48
It doesn't matter when you downloaded it, if you're upgrading from CI2, it's still the same upgrade procedure.
