### ISSUE TITLE
$this->db->update_batch() not compatible with MySQL 5.7

### ISSUE THREAD

**Issue by karenbchelp** [bcit-ci/CodeIgniter#4935] opened 2016-12-08 10:35 UTC
Hi!

Before the update the $this->db->update_batch() was just working fine. Now it gives an error:

```
ERROR - 2016-12-08 10:48:46 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'THEN '434'
WHEN `Contact_ID` =  THEN '896'
ELSE `Contact_ID` END, `FirstName` = ' at line 2 - Invalid query: UPDATE `Emergency_Contacts` SET `Contact_ID` = CASE 
WHEN `Contact_ID` =  THEN '434'
WHEN `Contact_ID` =  THEN '896'
ELSE `Contact_ID` END, `FirstName` = CASE 
WHEN `Contact_ID` =  THEN 'Big Mamma'
WHEN `Contact_ID` =  THEN 'Big Pappa'
ELSE `FirstName` END, `LastName` = CASE 
WHEN `Contact_ID` =  THEN 'Dog'
WHEN `Contact_ID` =  THEN 'Doggie'
ELSE `LastName` END, `PhoneNumber` = CASE 
WHEN `Contact_ID` =  THEN '78974945'
WHEN `Contact_ID` =  THEN '7889456465'
ELSE `PhoneNumber` END, `Relation` = CASE 
WHEN `Contact_ID` =  THEN 'mother'
WHEN `Contact_ID` =  THEN 'Father'
ELSE `Relation` END
WHERE `Contact_ID` IN(,)
```

My Code:

```
foreach($contacts->result() as $rowContact){				
		$tempContact = array(
		'Contact_ID' => $rowContact->Contact_ID,
		'FirstName' => $this->input->post('FirstName'.$rowContact->Contact_ID),
		'LastName' => $this->input->post('LastName'.$rowContact->Contact_ID),
		'PhoneNumber' => $this->input->post('PhoneNumber'.$rowContact->Contact_ID),
		'Relation' => $this->input->post('Relation'.$rowContact->Contact_ID)
	);
	
	array_push($contactDetails, $tempContact);				
}

if ($this->db->update_batch('Emergency_Contacts', $contactDetails, 'Contact_ID')) {
	return TRUE;
 } else {
	return FALSE;
}
```

**Comment by narfbg** [comment] 2016-12-08 10:50
Before the update to ... what?

**Comment by karenbchelp** [comment] 2016-12-08 10:56
Before updating to MySQL to 5.7.

I have tried running the same lines of code in an application that is using MySQL 5.6 and it is working.

**Comment by narfbg** [comment] 2016-12-08 10:58
Which CI version is that?

**Comment by karenbchelp** [comment] 2016-12-08 11:02
3.1.2

**Comment by narfbg** [comment] 2016-12-08 11:05
And you're really sure that the MySQL upgrade causes the issue, and this is not a duplicate of #4892?

**Comment by karenbchelp** [comment] 2016-12-08 11:14
I'm not 100% sure that MySQL version is the issue but it is not the escaping of the values that causes the issue. Because as I have posted above the query that was generated by CI is:

```
UPDATE `Emergency_Contacts` SET `Contact_ID` = CASE 
WHEN `Contact_ID` =  THEN '434'
WHEN `Contact_ID` =  THEN '896'
ELSE `Contact_ID` END, `FirstName` = CASE 
WHEN `Contact_ID` =  THEN 'Big Mamma'
WHEN `Contact_ID` =  THEN 'Big Pappa'
ELSE `FirstName` END, `LastName` = CASE 
WHEN `Contact_ID` =  THEN 'Dog'
WHEN `Contact_ID` =  THEN 'Doggie'
ELSE `LastName` END, `PhoneNumber` = CASE 
WHEN `Contact_ID` =  THEN '78974945'
WHEN `Contact_ID` =  THEN '7889456465'
ELSE `PhoneNumber` END, `Relation` = CASE 
WHEN `Contact_ID` =  THEN 'mother'
WHEN `Contact_ID` =  THEN 'Father'
ELSE `Relation` END
WHERE `Contact_ID` IN(,)
```

The "Contact_ID" should not be included in the fields to be updated and "unique keys" are not added in the "IN(,)" function.
The values in this query is the same as the one that I have entered.

**Comment by narfbg** [comment] 2016-12-08 11:19
Right ... it is a duplicate of #4892 then. Follow that one.

**Closed by narfbg** 2016-12-08 11:19 UTC
