### ISSUE TITLE
Doucumentation View is not showing properly on mobile view 320px

### ISSUE THREAD

**Issue by hqasraful** [bcit-ci/CodeIgniter#4912] opened 2016-11-18 06:50 UTC
Dear Sir,
             I read daily **## codeigniter** user guide via offline daily on mobile .I am facing problem to read on mobile the user guide offline on 320px  for the **latest Version 3.1.2**. It break the **html** norm .I attached the image also taken from **Mozilla** at 320px. Please fix it.

Thanks
Asraful Haque
![codeigniter user guide codeigniter 3 1 2 documentation](https://cloud.githubusercontent.com/assets/7779509/20421346/4e35f4b8-ad89-11e6-912c-4bedb4ec9da4.png)

hq.asraful@gmail.com

**Comment by narfbg** [comment] 2016-11-22 10:45
I don't really care about the docs working on mobile browsers, but our last 2 doc builds were indeed broken ... We've fixed them, does it display correctly now?

**Comment by hqasraful** [comment] 2016-11-22 12:12
Dear Sir,
           Thanks for your response. But I need it because I have only one
source to study it on Mobile. I use Firefox and Chrome . On both browsers
it is broken. If you fixed it , it will be helpful for me!

Thanks





*Asraful Haque*
*hq.asraful@gmail.com <hq.asraful@gmail.com>*
*wintellect.asraful@gmail.com <wintellect.asraful@gmail.com>*
*Mob: +91-7042805660*

**Comment by narfbg** [comment] 2016-11-22 12:23
You'll have a very hard time convincing me that you're programming on a mobile device with a 320px-wide screen, which is the only case you'd really "need" it.

But beside that, you didn't directly answer my question - after trying to open it *now*, is it still not displaying properly for you?

**Comment by hqasraful** [comment] 2016-11-23 04:55
Dear Sir,
          I wrote you that *I have only one source to study it on Mobile
but not programming* . How can I program on mobile! I used CodeIgniter
project in our small office but love to study on Mobile browser at home. I
don't have any PC/Laptop.

         *Yes , Still is same problem.It is broken.*

Thanks for your swift response!




*Asraful Haque*
*hq.asraful@gmail.com <hq.asraful@gmail.com>*
*wintellect.asraful@gmail.com <wintellect.asraful@gmail.com>*
*Mob: +91-7042805660*

**Comment by jim-parry** [comment] 2016-11-23 05:38
I just tested the user guide on my Samsung Rugby, running Android 4.1.2.
The classic layout button does not appear top right, in any orientation.
Going back to my desktop, the classic layout button appears at higher resolutions (which is what I tested originally), but disappears at "small" and "extra-small" window sizes (<772px, it would seem).

I went back to the CI 3.1.0, where the classic layout button appeared "normally", but it disappeared at "small" window size too. The same happens with the CI 3.0.6 user guide. 

Conclusion: I suspect that the classic layout button may have been not visible at smaller window sizes for some time now, and that that is an issue possibly unrelated to the current fix :(

@hqasraful Which is the newest version of CI where you noticed the user guide having a working classic layout button visible at smaller resolutions?

**Comment by hqasraful** [comment] 2016-11-23 07:20
Dear Sir ,
            I am tired to explain . I have attached three images. All Snapshot taken on the 320px basic!

> Show pretty good! Old version


![welcome to codeigniter codeigniter user guide](https://cloud.githubusercontent.com/assets/7779509/20553467/e5560c9e-b17a-11e6-86d1-dc69a69911a7.png)


> Show nothing on codeigniter 3 1 2 documentation

![codeigniter user guide codeigniter 3 1 2 documentation](https://cloud.githubusercontent.com/assets/7779509/20553367/22296022-b17a-11e6-9555-7fbb4260439e.png)
**After some change of the theme.js file on line no 43** 
`(// $('.wy-nav-content-wrap').css({background: 'none repeat scroll 0 0 #fcfcfc;', 'margin-left': '300px'});)`

> My content shows just perfect except Classic Layout

![codeigniter user guide codeigniter 3 1 2 documentation](https://cloud.githubusercontent.com/assets/7779509/20553447/d18a176e-b17a-11e6-8db1-412aee2846b3.png)


Thanks 
Asraful Haque
hq.asraful@gmail.com

**Comment by hqasraful** [comment] 2016-11-23 07:26
Sorry to include that I am using current version CodeIgniter Version 3.1.2. It is also showing classic button but now working(create event).

**Comment by narfbg** [comment] 2016-11-23 10:59
Well, I'm tired of this too.

@jim-parry All is up to you here.

**Comment by mixinix** [comment] 2016-11-23 19:57
I think, just remove the old button version 2 and upgrade the new Sphinx RTD Theme with a little customization.

**Comment by jim-parry** [comment] 2016-11-24 04:25
The latest version of Sphinx causes other issues, like the button disappearing altogether at all sizes :(

It could be that a fresh implementation of the feature, and/or getting to the bottom of the latest Sphinx problems, would be a logical next step ... for someone more familiar with Sphinx, and with some time to put into the task.

The CI4 user guide has the same issue, with the classic layout button disappearing at smaller screen sizes. 

This needs to be solved at some point, but doesn't feel like a high priority compared to the other work on our plates :(

@hqasraful Have you tried the epub format of the user guide? I seem to recall us adding that becuase of a community member wanting to read the guide on their tablet or smartphone.

**Comment by ml054** [comment] 2017-11-15 09:03
This is how it looks on my Samsung Galaxy S7 Edge: 


![screenshot_20171115-095905](https://user-images.githubusercontent.com/1250431/32827346-237d5e7a-c9ec-11e7-8e79-4b48da26a3ad.png)

**Comment by HyndexCoder** [comment] 2017-12-21 08:51
I have also experienced this problem. It should be fixed.

**Comment by reeslo** [comment] 2018-01-17 19:53
Same on One plus one with Firefox

**Comment by mehdibo** [comment] 2018-01-29 02:55
I think I have a fix for this but I need a confirmation, why is the `section.wy-nav-content-wrap` element's margin-left is set to 300px?

**Comment by mehdibo** [comment] 2018-01-29 03:13
This is what causes the problem.
Line 43 in [theme.js](https://github.com/mehdibo/CodeIgniter/blob/develop/user_guide_src/source/_themes/sphinx_rtd_theme/static/js/theme.js):

`$('.wy-nav-content-wrap').css({background: 'none repeat scroll 0 0 #fcfcfc;', 'margin-left': '300px'});`

I added a breakpoint and it solved it:
![before](https://user-images.githubusercontent.com/5004111/35492009-115c0a5c-04a2-11e8-8a64-f5ceb740a243.png)

And after stepping over:
![after](https://user-images.githubusercontent.com/5004111/35492035-2930d70c-04a2-11e8-9797-c7086effa965.png)


What I don't though is, why is this code there in the first place? is it safe to remove it? I tried manually removing the `margin-left` style and it worked just fine in both Mobile view and Laptop view.

**Comment by narfbg** [comment] 2018-01-29 08:15
No idea and the guy who wrote that is no longer involved with us.

@jim-parry Do you happen to be familiar with that?

**Comment by Elias-Black** [comment] 2018-01-30 15:26
Problem at 25 line of https://github.com/bcit-ci/CodeIgniter/blob/develop/user_guide_src/source/_themes/sphinx_rtd_theme/static/js/theme.js file.

Toggle not corresponds to definition http://api.jquery.com/toggle/

I'll see this when I have a little more time...

**Comment by jim-parry** [comment] 2018-02-14 18:14
Hmm - I thought this had been fixed, but obviously not.

@Elias-Black A 300px margin is mentioned in two places: lines 43 and 99. Are you suggesting that only the one should be changed?

There was a suggestion emailed to me that one/some of the screen width tests should be looking for a width of 980, presumably in place of 768. Does this make sense?

**Comment by Elias-Black** [comment] 2018-02-14 19:38
@jim-parry about the resolution of 768 and 980 pixels: no, it does not make sense. Code from 83 to 101 line works on resize only... I have the bug without entering to these conditions.

Line 43 works on load the pages.

**Comment by maciejcieslik** [comment] 2018-02-14 20:20
Problem is in /user_guide/_static/js/theme.js

here: 
$('.wy-nav-content-wrap').css({background: 'none repeat scroll 0 0 #fcfcfc;', 'margin-left': '300px'});

just wrap it in if statement like that:

if ($(window).width() > 980) {
  $('.wy-nav-content-wrap').css({background: 'none repeat scroll 0 0 #fcfcfc;', 'margin-left': '300px'});
}

**Comment by om-mahato** [comment] 2019-04-05 10:48
Hello, I checked the documentation on mobile and this is still the same. The issue is still there. 
   The problem is when the DOM is ready inline style "margin-left: 300px;" is get added to the section.
One simple fix i came with is adding !important to the css media query here:
[file](https://codeigniter.com/user_guide/_static/css/theme.css) at **line: 4**

```
@media screen and (max-width: 768px)
.wy-nav-content-wrap {
     - margin-left: 0;
    + margin-left: 0 !important;
}
```
This seems to solve the issue.

**Comment by narfbg** [comment] 2019-04-07 18:05
@jim-parry Again, leaving this one all up to you. I suck at front-end stuff anyway ... :)

**Comment by jim-parry** [comment] 2019-04-23 16:11
Hopefully put to bed :)

**Closed by jim-parry** 2019-04-23 16:11 UTC
Labels: Documentation
