### ISSUE TITLE
Session with database inserting data continuously

### ISSUE THREAD

**Issue by hellofarhan** [bcit-ci/CodeIgniter#3661] opened 2015-03-12 14:05 UTC
I am using session with database. Data is inserting continuously. I don't know what is going on.

**Comment by narfbg** [comment] 2015-03-12 14:54
What do you mean by continuously?

**Comment by hellofarhan** [comment] 2015-03-12 16:33
After configure the session storage as database in testing server I checked the session table. Each and every second the session row is inserting into session table. until now table row is increasing one by one.

**Comment by narfbg** [comment] 2015-03-12 16:36
Did you make sure you cookie settings are correct? Specifically the domain and path parts must match those of your site's location.

**Comment by hellofarhan** [comment] 2015-03-12 16:44
Yes I checked. It has the default configuration and my domain is not subdomain. And before session driver was cookie with database. on that time it was working perfectly. After upgrading of new version of CI it is happening.

**Comment by narfbg** [comment] 2015-03-12 16:50
Did you change your database structure accordingly then?

**Comment by hellofarhan** [comment] 2015-03-12 16:53
Yes of course. I followed all steps from this link http://www.codeigniter.com/userguide3/libraries/sessions.html

**Comment by narfbg** [comment] 2015-03-12 17:22
Please post your session and cookie settings.

**Comment by hellofarhan** [comment] 2015-03-12 17:32
$config['sess_driver'] = 'database';
$config['sess_cookie_name'] = 'KingSession';
$config['sess_expiration'] = 0;
$config['sess_save_path'] = 'king_sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

$config['cookie_prefix']	= ''";
$config['cookie_domain']	= ''";
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;

**Comment by narfbg** [comment] 2015-03-12 17:38
Hmm ... and what is the domain name that you use to access that?

**Comment by hellofarhan** [comment] 2015-03-12 18:07
for the security purpose i moved to another subdomain. http://alpha.mazadsale.com
And i updated the path. 

$config['cookie_domain'] = ''alpha.mazadsale.com";

still same issue.

**Comment by hellofarhan** [comment] 2015-03-12 19:47
I restarted the server. Still increasing session rows.

**Comment by hellofarhan** [comment] 2015-03-13 04:27
After lots of works I found the problem. I am using varnish cache with apache. The problem is if I disable varnish cache everything working fine but if I enable the varnish cache again it is starting to insert session rows each and every second. I am using the following varnish configuration. https://github.com/mattiasgeniar/varnish-4.0-configuration-templates/blob/master/default.vcl

**Comment by narfbg** [comment] 2015-03-13 09:28
I see ...

Well, you might have more luck if you ask for help on the [forums](http://forum.codeigniter.com/). Closing this now as it is deffinately not a bug.

**Closed by narfbg** 2015-03-13 09:28 UTC
