### ISSUE TITLE
dbprefix not added to Like Clause in 3.1.8

### ISSUE THREAD

**Issue by DavidTurnerDotInfo** [bcit-ci/CodeIgniter#5474] opened 2018-04-18 12:46 UTC
My code was working with 3.1.7 but since updating to 3.1.8 the following instruction no longer receives the table prefix in the MySQL output.  

$this->db->like('Blocks.BlockType',$val);

I'm using the following config;
$db['dbdriver'] = "mysqli"; 
$db['dbprefix'] = "myprefix_";
$db['pconnect'] = FALSE;
$db['db_debug'] = TRUE;
$db['cache_on'] = FALSE;
$db['cachedir'] = "";
$db['char_set'] = "utf8";
$db['dbcollat'] = "utf8_general_ci";

**Comment by narfbg** [comment] 2018-04-18 12:57
Duplicate of #5448.

Please search for existing issues before opening new ones.

**Closed by narfbg** 2018-04-18 12:57 UTC

**Comment by DavidTurnerDotInfo** [comment] 2018-04-18 13:10
Thanks. Sorry, It hadn't come up in my search.  Glad to see it's sorted
