### ISSUE TITLE
Transaction not working?

### ISSUE THREAD

**Issue by psuplat** [bcit-ci/CodeIgniter#5399] opened 2018-02-02 15:57 UTC
Hi,

I just came across an issue with the transactions.

One of my applications runs a set of insert, update & delete queries affecting records in 6 different tables, sometime easily going over 50 queries.

All of the queries are run using Query Builder, so my code looks something like this:
```
$this->db->trans_start();
$this->db->set('table1_field',$value1)->insert('table1');
$this->db->set('table2_field',$value2)->where('id',$update_record_id)->update('table2');
$this->db->where('id',$delete_record_id)->delete('table3');
$this->db->trans_complete();
```
I noticed that some of the queries failed, because I mis-typed the name of the field or table.
However the _$this->db->trans_status()_ returned TRUE and rather then the transaction being rolled back, all the queries that compiled successfully got committed, and those that failed not.

According to CI manual running transactions & managing errors should be run like so:
```
$this->db->trans_start();
$this->db->query('AN SQL QUERY...');
$this->db->query('ANOTHER QUERY...');
$this->db->trans_complete();

if ($this->db->trans_status() === FALSE)
{
        // generate an error... or use the log_message() function to log your error
}
```

I know it may sound like a daft question, so please forgive my ignorance, but does this literally suggest I cannot use Query Builder inside transaction, but have to execute queries by using _$this->db->query()_ ?

or should I always run transaction like so:
```
$this->db->trans_begin();
$this->db->query('AN SQL QUERY...');
$this->db->query('ANOTHER QUERY...');
$this->db->query('AND YET ANOTHER QUERY...');

if ($this->db->trans_status() === FALSE)
{
        $this->db->trans_rollback();
}
else
{
        $this->db->trans_commit();
}
```

but than again _$this->db->trans_status()_ returned true so I can't see a difference that this would make

Anything else I might be missing?

I looked at issue #3098 but in my case strict mode is not disabled, so I don't think same applies

The DB is MSSQL

**Comment by narfbg** [comment] 2018-02-05 07:25
> I noticed that some of the queries failed, because I mis-typed the name of the field or table.
> However the *$this->db->trans_status()* returned TRUE and rather then the transaction being rolled back, all the queries that compiled successfully got committed, and those that failed not.

Is it just `trans_status()` returning TRUE that's the issue or did you verify that data was committed?

>
> ...
>
> I know it may sound like a daft question, so please forgive my ignorance, but does this literally suggest I cannot use Query Builder inside transaction, but have to execute queries by using *$this->db->query()* ?

The docs on this are bad, but no - that's not at all suggested, I don't know how you came to that conclusion.

> I looked at issue #3098 but in my case strict mode is not disabled, so I don't think same applies

It looks quite the same to me.

**Comment by psuplat** [comment] 2018-02-05 09:58
> Is it just trans_status() returning TRUE that's the issue or did you verify that data was committed?

I verified that the data got committed in the DB. 

> The docs on this are bad, but no - that's not at all suggested, I don't know how you came to that conclusion.

Oh, you would be surprised how many times I came across situations were the things had to be done literally as said in the docs, a tiny deviation caused things to fall over - 
"_Yes! You can do all those amazing magical things! Oh, that?  Well, that's that one small exception_" :)

> It looks quite the same to me.

Except it implies the issue exists only when strict mode is used - not my case.
But I will check it anyway. I will be too tied up today to try, but I will get back to you tomorrow with some results.

**Comment by psuplat** [comment] 2018-02-07 10:42
Oops, I guess first of all  I need to apologize for the confusion in my last reply. I run my transactions in strict mode, I do not use the $this->db->trans_strict(FALSE) as is the case in #3098.

Nevertheless the trans_status() still returns TRUE even if any of the queries fail. If I follow the 
```
$trans_begin();
//bunch of queries here
if ($this->db->trans_status() === FALSE) 
{ 
    $this->db->trans_rollback(); 
}
else
{ 
    $this->db->trans_commit();
}
```
everything works fine. I guess I will change the way I work with transaction to that way. No biggie really, and I guess it's always better to check _before_ you do some potential damage.

As a side note, I have not tested this behavior with any other RMDB's other then MSSQL (simply lack of time).

**Comment by akarupt** [comment] 2018-06-09 13:11
Codeigniter 3.1.8:

$this->db->trans_begin();
$this->db->query("update ateste set count = count + 1;");
$this->db->trans_rollback();

I run that on a migration. Data commited anyway...

**Comment by almatins** [comment] 2019-01-14 03:44
why does this issue still have the status: open ?

**Comment by psuplat** [comment] 2019-01-14 19:15
Perhaps because the issue was not really solved. I just had change the way I used transactions, ergo workaround not a solution

**Comment by narfbg** [comment] 2019-02-14 18:18
Um, sorry for not getting back at this for so long.

I only have MySQL to test with, so with you using MSSQL that doesn't mean much, but I can't reproduce it ...
I'd say we have pretty reliable abstractions, so I'm inclined to trust my own result, but we do have 4 drivers that can run on MSSQL - if you can specify which one is misbehaving, I can at least look at the code.

**Comment by psuplat** [comment] 2019-02-15 17:24
It was the sqlsrv (I guess that is what you're asking for)

**Comment by narfbg** [comment] 2019-02-18 15:15
Well, unless `sqlsrv_query()` wouldn't return FALSE in some failure cases, I don't see how the behavior that you described is possible.

**Closed** 2022-01-05 20:40 UTC
