### ISSUE TITLE
User guide small error

### ISSUE THREAD

**Issue by AzaZPPL** [bcit-ci/CodeIgniter#5360] opened 2017-12-14 12:22 UTC
There is a small error on https://www.codeigniter.com/userguide3/general/urls.html
The rewrite is in text

**Comment by plonknimbuzz** [comment] 2017-12-16 17:44
yes. but it was fixed on this commit https://github.com/bcit-ci/CodeIgniter/commit/ea21f113733e914d5d0c950d5bfb5c5624368407

**Comment by jim-parry** [comment] 2017-12-16 18:07
Already fixed, as noted above.

**Closed by jim-parry** 2017-12-16 18:07 UTC

**Comment by narfbg** [comment] 2017-12-20 15:13
Marking as duplicate of #5283.
