### ISSUE TITLE
Routing: URI vars dont pass if the controller has the same name like the public function 

### ISSUE THREAD

**Issue by SineMathur** [bcit-ci/CodeIgniter#4612] opened 2016-05-04 17:18 UTC
Hey,
probably no1 except me usng this constallation.
Today i wrote a controller which got the name _save _and a public function _save_.
i tried to pass 2 variables to the controller with a request.

```
class Save extends CI_Controller {

	public function save($name, $data) {
		
	}
}
```

The vars were undefined when i called it.

> 192.168.204.133/project/index.php/save/save/123.log/abc

I tried to fix it with routing but it doesnt work aswell.
Just renaming the function or controller solved the issue.

Greetings
Chris

**Comment by narfbg** [comment] 2016-05-05 00:49
Duplicate of #3451.

**Closed by narfbg** 2016-05-05 00:49 UTC
Labels: Duplicate
