### ISSUE TITLE
Pagination class bug

### ISSUE THREAD

**Issue by Den4X** [bcit-ci/CodeIgniter#5238] opened 2017-08-27 12:36 UTC
On \system\libraries\Pagination.php line 357 need to change
`if (is_array($params['attributes'])`
to
`if (is_array($params['attributes']) && !empty($params['attributes']))`

without this check attributes from pagination config will erased on pagination->initialize if new attributes not sent

**Comment by narfbg** [comment] 2017-08-28 08:34
Sorry, I don't understand what the problem is.

**Comment by masterZSH** [comment] 2017-10-16 09:01
don't worry,if $params['attributes'] is empty ,is_array($params['attributes'])==false.

**Comment by narfbg** [comment] 2017-10-16 09:09
Depends on what is meant by "empty". `is_array(array())` will return `true`.

That still doesn't explain what the problem is though. Closing after 2 months without feedback.

**Closed by narfbg** 2017-10-16 09:09 UTC
