### ISSUE TITLE
prevent to add space in select statement

### ISSUE THREAD

**Issue by plonknimbuzz** [bcit-ci/CodeIgniter#4976] opened 2017-01-11 04:15 UTC
```
$this->db->select("replace(topic, ',', '') AS topic",  FALSE);
$this->db->get('opub_tag');
```
result:
`SELECT replace(topic, ', ', '') AS topic FROM "opub_tag"`

that added SPACE on replace(topic, ',[SPACE]', '')  which shouldnt happen

i try
```
$this->db->_protect_identifiers = FALSE;
$this->db->select("replace(topik, ',', '') AS topik",  FALSE);
$this->db->get('opub_tag');
$this->db->_protect_identifiers = TRUE;
```

but thats give me error : 

> Fatal error: Cannot access protected property CI_DB_pdo_sqlsrv_driver::$_protect_identifiers in C:\xampp\htdocs\frontend\application\controllers\frontend_kliping.php on line 1133

what i want is like this `SELECT replace(topic, ',', '') AS topic FROM "opub_tag"`

i prevent to use `$this->db->query("SELECT REPLACE(topic, ',','') AS topic FROM opub_tag")`
because i have many parameter in that real query and i dont want to break my behaviour to using query builder as long as i can.

i try to search on google but cant get the answer.

what should i do for doing this?

**Comment by narfbg** [comment] 2017-01-11 10:09
Duplicate of #634.

**Closed by narfbg** 2017-01-11 10:09 UTC
Labels: Duplicate
