### ISSUE TITLE
[Feature Request] Feature to delete cache

### ISSUE THREAD

**Issue by rajbdilip** [bcit-ci/CodeIgniter#5080] opened 2017-04-05 18:22 UTC
Wouldn't it be nice to have an option to delete caches natively in CodeIgniter? There are third-party modules like https://github.com/stevenbenner/codeigniter-cache-helper. I personally find myself having to delete cache, individually, all or just expired ones, frequently. Or this feature hasn't been included to keep the framework minimal?

**Comment by narfbg** [comment] 2017-04-06 10:05
Duplicate of #609.

https://codeigniter.com/userguide3/general/caching.html#deleting-caches

**Closed by narfbg** 2017-04-06 10:05 UTC
Labels: Duplicate
