### ISSUE TITLE
Message: ctype_digit(): Argument of type null will be interpreted as string in the future  Filename: libraries/Pagination.php  Line Number: 526

### ISSUE THREAD

**Issue by lisheng51** [bcit-ci/CodeIgniter#6143] opened 2022-06-23 21:12 UTC
https://www.php.net/manual/en/function.ctype-digit.php

simple fix：
ctype_digit((string)$this->cur_page)

**Comment by tenzap** [comment] 2022-07-04 10:22
Duplicate of #6119 ?

**Closed as completed** 2023-03-22 00:05 UTC
Labels: Duplicate
