### ISSUE TITLE
Transaction status in loop not reset

### ISSUE THREAD

**Issue by ymchun** [bcit-ci/CodeIgniter#5246] opened 2017-09-04 11:40 UTC
Consider the following code

```PHP
<?php

foreach($users as $user){
	$this->db->trans_begin();

	$this->db->query('some sql 1');
	$this->db->query('some sql 2');
	$this->db->query('some sql 3');

	if($this->db->trans_status() === FALSE){
		$this->db->trans_rollback();
	}
	else{
		$this->db->trans_commit();
	}
}
```

I am using this code to loop an user array to create users.
Each loop need to use 3 query to create a single user eg. insert user info, insert permission, ...

My expectation:
When some users failed, skip that user and rollback. Then continue to create users after that.

But the thing I got:
$this->db->trans_status() always return FALSE when something failed in the middle, all users got rolled back after one user failed.

I think $this->db->trans_status() never reset when doing commit or rollback.

CI version: 3.1.5
PHP version: 5.6.31
Server: Windows Server 2012 R2

**Comment by ymchun** [comment] 2017-09-04 11:49
#4026
duplicated

**Comment by narfbg** [comment] 2017-09-04 12:04
This is not a duplicate of #4026.

That was about failed queries *outside of a transaction* causing future rollbacks, and was fixed in 3.0.1. If it was the same issue, you wouldn't be experiencing it on 3.1.5.

**Comment by narfbg** [comment] 2017-09-04 12:14
Try with the commit linked above.

**Comment by ymchun** [comment] 2017-09-04 12:25
seems good

**Comment by narfbg** [comment] 2017-09-04 12:43
Great, closing then.

**Closed by narfbg** 2017-09-04 12:43 UTC
Labels: Bug
