### ISSUE TITLE
Form Validation Callback

### ISSUE THREAD

**Issue by hamlington** [bcit-ci/CodeIgniter#5160] opened 2017-06-22 08:57 UTC
Hi,

I believe there is a bug in the form validation callback function. As I understand it, it should run the rules in order left to right, and stop when it finds an error without running the rest.

$this->form_validation->set_rules('email','email','required|valid_email|callback_emailCheck');

But I am finding that if the emailCheck method meets the criteria where it returns false, then even though other rules would have failed before hand it takes priority on the error message.

my emailCheck method uses an account model to check whether an email address exists, if it doesn't then return false with: 

if($arr['result']!==false){$this->form_validation->set_message('uniqueEmailCheck',$this->lang->line('form_validation_email_missing')); unset($arr); return(false);}

in the form I type in on the email address field 'k', which is not a valid email address, but instead of it reporting that back to me it reports back: "The {field} was not found on our system." which is the 'form_validation_email_missing' message.

Can anyone confirm this is a bug, if I drop the call back then the rules work correctly in order, for some reason it seems to priority over everything else if it reports false.

**Comment by narfbg** [comment] 2017-06-22 08:59
Duplicate of #5077.

**Closed by narfbg** 2017-06-22 08:59 UTC
