### ISSUE TITLE
get_request_header does not work

### ISSUE THREAD

**Issue by a432511** [bcit-ci/CodeIgniter#4071] opened 2015-08-24 00:21 UTC
Good evening,

The get_request_header method does not appear to be working.

$this->input->get_request_header('Authorization'); returns null

However, if I call $this->input->request_headers(); and then make the call to $this->input->get_request_header('Authorization'); it appears to function correctly. I took a peek at the code and it appears something is wrong with the enumeration of the static $headers variable.

Cheers,

Adam

**Comment by narfbg** [comment] 2015-08-24 10:04
Duplicate of #4056.

**Closed by narfbg** 2015-08-24 10:04 UTC
