### ISSUE TITLE
File upload stopped working after updating from 3.1.0 to 3.1.2

### ISSUE THREAD

**Issue by infyond** [bcit-ci/CodeIgniter#4898] opened 2016-11-03 01:12 UTC
Hello,
After updating from 3.1.0 to 3.1.2 , file upload stopped working and a blank page (error 500) starts showing up, no errors, no logs.

After re-uploading the system directory of 3.1.0 version everything works fine again.

Here is the code:

```
$config['upload_path']          = './uploads/new/';
$config['allowed_types']        = 'jpg|gif|png|jpeg';
$config['max_size']             = 2000;
$config['max_width']            = 5000;
$config['max_height']           = 3000;
$config['file_name']            = 'name_'.$id;
$config['overwrite']            = TRUE;
$config['file_ext_tolower']     = TRUE;

$this->load->library('upload', $config);

if ( ! $this->upload->do_upload('field_name'))
{
		$error = $this->upload->display_errors();
		$this->session->set_flashdata('message', "{$error}");
}
```

**Comment by toyza55k** [comment] 2016-11-03 03:40
Can you check your "extension=php_fileinfo.dll" in php.ini
Is it enabled?

**Comment by infyond** [comment] 2016-11-03 05:52
This extension wasn't installed on the server, I installed and now it works, thanks.

But I'm confused, is this a new requirement for CodeIgniter file Upload library to work? (because it works fine without this on version 3.1.0)

This is unfortunate, now the script won't work on most shared hostings.

Thanks again.

**Comment by narfbg** [comment] 2016-11-03 08:53
Duplicate of #4887.

**Closed by narfbg** 2016-11-03 08:53 UTC
Labels: Duplicate
