### ISSUE TITLE
Form validation piping not working as expeted

### ISSUE THREAD

**Issue by nikolayanchev** [bcit-ci/CodeIgniter#5509] opened 2018-05-25 09:45 UTC
I have  recently noticed that the piping of form validation rules doesn't work as expected by the term piping, the ordering of called rules is scrambled. for example if you have rules set up like that 
`trim|required|xss_clean|exact_length[7]|alpha_numeric|callback_checkCode|callback_checkUsedCode`
the call sequence comes out like this 
`   [0] => trim
    [1] => xss_clean
    [2] => callback_checkCode
    [3] => callback_checkUsedCode
    [4] => required
    [5] => exact_length[7]
    [6] => alpha_numeric
`
Shouldn't the sequence be as defined in the string?

**Comment by gxgpet** [comment] 2018-05-25 10:11
Duplicate of #5077.

**Closed** 2018-05-25 10:21 UTC
