### ISSUE TITLE
create_links() Pagination does not take routing into account

### ISSUE THREAD

**Issue by NielsDev** [bcit-ci/CodeIgniter#4215] opened 2015-11-05 00:21 UTC
Can be solved by changing Pagination.php
Change line 505 into: $this->uri_segment = count($this->CI->uri->rsegment_array());
Change line 508 into: $this->cur_page = $this->CI->uri->rsegment($this->uri_segment);

**Comment by narfbg** [comment] 2015-11-05 09:05
Duplicate of #1909.
Also relevant: #2199

**Closed by narfbg** 2015-11-05 09:05 UTC

**Comment by NielsDev** [comment] 2015-11-05 14:06
It seems that this has been an issue that was fixed in the past.
However, for some reason, this issue has returned.

**Comment by narfbg** [comment] 2015-11-05 14:18
The library can't work out of the box under all conditions and making it work under this one introduces other issues, which is why the fix didn't last long and was changed.
