### ISSUE TITLE
escape_like_str a database bug feedback

### ISSUE THREAD

**Issue by yuchonghua** [bcit-ci/CodeIgniter#4540] opened 2016-03-17 09:42 UTC
$ Sql = 'LIKE "%' $ this-> db-> escape_like_str ( '_') '%.."';
Will generate
$ Sql = 'LIKE "% _%!"';
The need to '!' To ci phpfile \ system \ database \ DB_driver.php 338 rows '\\'
原文[中文]：
$sql = 'LIKE "%'.$this->db->escape_like_str('_').'%"';
会生成
$sql = 'LIKE "%!_%"';
需要把ci phpfile\system\database\DB_driver.php 的 338行的 '!'改为'\\'
![ci_bug](https://cloud.githubusercontent.com/assets/17898715/13842147/a15b117a-ec67-11e5-9495-08be235dea1e.png)
@wmh @joshk @appleboy @kitsunde @wuwx 
[http://codeigniter.org.cn/forums/thread-22297-1-1.html](url)

**Comment by narfbg** [comment] 2016-03-17 09:52
Duplicate of #4462.

**Closed by narfbg** 2016-03-17 09:52 UTC
Labels: Duplicate
