### ISSUE TITLE
Broken "Config Class" Link on Handling Multiple Environments in Documentation

### ISSUE THREAD

**Issue by denisa93** [bcit-ci/CodeIgniter#3948] opened 2015-07-03 04:14 UTC
http://www.codeigniter.com/user_guide/general/environments.html

The broken link there is on this sentence

Optionally, you can have CodeIgniter load environment-specific configuration files. This may be useful for managing things like differing API keys across multiple environments. This is described in more detail in the environment section of the Config Class documentation.

**Comment by narfbg** [comment] 2015-07-03 08:07
Duplicate of #3851.

**Closed by narfbg** 2015-07-03 08:07 UTC
Labels: Duplicate
