### ISSUE TITLE
Log levels do not follow industry standards

### ISSUE THREAD

**Issue by sprakashtd** [bcit-ci/CodeIgniter#4487] opened 2016-02-26 17:40 UTC
Codeigniter logging severity levels are currently in this order: ERROR - DEBUG - INFO
This does not follow industry standards and should be re-ordered to ERROR - INFO - DEBUG

**Comment by narfbg** [comment] 2016-02-26 17:54
Duplicate of #1481, #1522.

**Closed by narfbg** 2016-02-26 17:54 UTC
Labels: Duplicate
