### ISSUE TITLE
BUG: Incorrect decoding db-name which contains a dot-character ('.')

### ISSUE THREAD

**Issue by vyshkant** [bcit-ci/CodeIgniter#3719] opened 2015-03-30 23:26 UTC
Hey!
Have been trying your CodeIgniter 3.0 and found a bug in the program.
I don't have enough time for seeking a reson, but I can tell you next:
1) I have a DB, which name contains a dot: e.g. `dbname.local`
2) I had pasted this db-name into my `/application/config/database.php` file into the string
`$db['default'] = array(..., 'database' => 'dbname.local', ...);` and my application still had been working.
3) Next I tried to make a hook like that:
```
$hook['post_controller_constructor'] = function() {
    $global_instance =& get_instance();
    $global_instance->load->library('migration');
    if ($global_instance->migration->current() === FALSE) {
        show_error($global_instance->migration->error_string());
    }
};
```
4) And i had had an error on line `$global_instance->load->library('migration');`
![screenshot-eztravel local 2015-03-31 02-01-09](https://cloud.githubusercontent.com/assets/4893820/6909219/8a4b4fc6-d74c-11e4-8a66-424ae74f7cba.png)
5) Than I found, that the error was occured at this part of your code in file `/system/libraries/Migration.php`, when system was trying to make new table in my DB.
```
		// If the migrations table is missing, make it
		if ( ! $this->db->table_exists($this->_migration_table))
		{
```

6) Next I have changed the DB-name on SQL-server and in config, and in started working.

**Comment by LouisMilotte** [comment] 2015-03-30 23:54
Schema objects must follow MySQL guidelines:
http://dev.mysql.com/doc/refman/5.7/en/identifiers.html

A "." in an object name is not to standard.

**Comment by vyshkant** [comment] 2015-03-31 02:48
As I can see, MySQL guidelines says that dot-character is allowed:
```
Permitted characters in quoted identifiers include the full Unicode Basic Multilingual Plane (BMP), except U+0000:
ASCII: U+0001 .. U+007F
Extended: U+0080 .. U+FFFF
```
In Unicode dot-character has code `U+002E`, which falls in the specified range of permitted characters ` U+0001 .. U+007F`.
Guideline says, that this character is allowed for *quoted identifiers*, but I think it is framework's area of responsibility, not developer's.

**Comment by LouisMilotte** [comment] 2015-03-31 05:14
You're right, my apologies.

**Comment by narfbg** [comment] 2015-03-31 08:57
This is pretty much a duplicate of #2755.

What MySQL or another datatabase allows and what CI allows are different things. CI makes some assumptions and one of them is that you use dots and commas to separate identifier names. In 99% of the time, that's the case and the effort to support a different case is not worth it.

**Closed by narfbg** 2015-03-31 08:57 UTC
