### ISSUE TITLE
Database Restore Issue 

### ISSUE THREAD

**Issue by sanjayacloud** [bcit-ci/CodeIgniter#5475] opened 2018-04-19 06:06 UTC
Hello,
I have create a database backup using codeigniter $this->load->dbutil(); This Work fine and I can download my database backup. But I try to restore this backup and I got below error..

SQL query:

INSERT INTO app_user (id, user_name, email, password, role, status) VALUES (10, Admin.sgh, admin@supreme.lk, 202cb962ac59075b964b07152d234b70, 0, 0)
MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@supreme.lk, 202cb962ac59075b964b07152d234b70, 0, 0)' at line 1

**Comment by narfbg** [comment] 2018-04-19 08:45
[Again](https://github.com/bcit-ci/CodeIgniter/issues/5472), a duplicate of #5276.

**Closed by narfbg** 2018-04-19 08:45 UTC
