### ISSUE TITLE
getting query results with specific unique column name

### ISSUE THREAD

**Issue by mohikan** [bcit-ci/CodeIgniter#5877] opened 2019-12-11 13:40 UTC
I think it can help a lots of people and save time, like bellow 

/system/database/DB_result.php
result method

	public function result($type = 'object', $key = null)
	{
		if ($type === 'array')
		{
			return $this->result_array($key);
		}
		elseif ($type === 'object')
		{
			return $this->result_object($key);
		}

		return $this->custom_result_object($type);
	}

result_object method :

	public function result_object($key = null) 
	{
		...

		if (is_null($key))
		{
			while ($row = $this->_fetch_object())
			{
				$this->result_object[] = $row;
			}
		}
		else
		{
			while ($row = $this->_fetch_object())
			{
				$this->result_object[$row->$key] = $row;
			}
		}

		return $this->result_object;
	}

result_array method :

	public function result_array($key = null)
	{
		...

		if(is_null($key))
		{
			while ($row = $this->_fetch_assoc())
			{
				$this->result_array[] = $row;
			}
		}
		else
		{
			while ($row = $this->_fetch_assoc())
			{
				$this->result_array[$row->$key] = $row;
			}			
		}

		return $this->result_array;
	}

**Comment by narfbg** [comment] 2020-01-14 10:19
Duplicate of #429.

**Closed by narfbg** 2020-01-14 10:19 UTC
