### ISSUE TITLE
parent::__construct() not running when controller/method name is the same

### ISSUE THREAD

**Issue by charj-it** [bcit-ci/CodeIgniter#4569] opened 2016-04-06 09:05 UTC
I found a weird bug when renaming some of our controllers..

I can load Foo/bar absolutely fine with no issues with code looking like this:

```
class Foo extends BF_Controller {

	public function bar() {
		$this->lang->load('example');
        }
}

```

But when I rename the method to Foo/foo, the construct doesn't run.

**Example Error output**
```
A PHP Error was encountered
Severity: Notice
Message: Undefined property: Foo::$lang
Filename: controllers/Foo.php
Line Number: 20

( ! ) Fatal error: Call to a member function load() on a non-object in /var/www/html/application/controllers/Foo.php on line 20
Call Stack
#	Time	Memory	Function	Location
1	0.0002	233968	{main}( )	../index.php:0
2	0.0012	237200	require_once( '/var/www/html/system/core/CodeIgniter.php' )	../index.php:293
3	0.0829	569200	Foo->foo( )	../CodeIgniter.php:500


A PHP Error was encountered
Severity: Error
Message: Call to a member function load() on a non-object
Filename: controllers/Foo.php
Line Number: 20

```
If I run the parent::_construct() manually, the code runs fine with the class and method names matching.

```
class Foo extends BF_Controller {
	function __construct () {
		parent::__construct();
	}

	public function foo() {
		$this->lang->load('example');
        }
}
```

I know this probably isn't best practice, but I thought I would raise it anyway as it stood out to me.

**Server Info:**

- CodeIgniter 3.0.4
- PHP Version 5.5.9-1ubuntu4.14
- Linux vagrant-ubuntu-trusty-64 3.13.0-55-generic #92-Ubuntu SMP Sun Jun 14 18:32:20 UTC 2015 x86_64

**Comment by narfbg** [comment] 2016-04-06 09:10
This is not a bug, but a legacy PHP feature that is [noted in the manual](https://codeigniter.com/userguide3/general/controllers.html#reserved-method-names).

**Comment by narfbg** [comment] 2016-04-06 09:11
Also, this is a duplicate of #3451.

**Closed by narfbg** 2016-04-06 09:11 UTC
Labels: Duplicate

**Comment by charj-it** [comment] 2016-04-06 09:25
Thanks @narfbg, I wasn't aware of this. You've taught me something :)
