### ISSUE TITLE
Image library

### ISSUE THREAD

**Issue by newdriv** [bcit-ci/CodeIgniter#4937] opened 2016-12-09 06:30 UTC
Have these issues when upgraded from 2.2.4 to 3.1.2
image_lib.php has issues. 
line 889
$cmd .= escapeshellarg($this->full_src_path).' '.escapeshellarg($this->full_dst_path).' 2>&1';
need to add space in front of it otherwise compiled command is wrong
as such 
$cmd .= ' '.escapeshellarg($this->full_src_path).' '.escapeshellarg($this->full_dst_path).' 2>&1';

also this library in general has problem
when used config for image processing 
i.e.
$config['source_image']	= './folder/path/'.$upload_info['file_name'];
$config['new_image'] ='./folder/path/'.$upload_info['file_name'];
compiles the $this->full_scr_path & $this->full_dst_path in the image_lib.php in initialise correctly in earlier version
but in latest version for above conf the path compile as 

$this->full_scr_path = correct absolute path converted and set here
$this->full_dst_path = incorrect absolute path i.e exact value of './folder/path/'.$upload_info['file_name']; which no good thus resulting in wrong commands

so had to modify them to 
$config['source_image']	='./folder/path/'.$upload_info['file_name'];
$config['new_image'] = FCPATH.'./folder/path/'.$upload_info['file_name']; which is inconsistent with the docs

**so two problems namely,**
1. space issue
2. relative directory not set properly in full_dst_path when used new_image config varible

**Comment by vkeranov** [comment] 2016-12-09 08:21
First of all... Latest version is 3.1.2 and I can't understand where you find this 3.1.6 version. And as far as I remember... The problem with this space was fixed a long time ago. So, try the latest (3.1.2) version first.

**Comment by newdriv** [comment] 2016-12-09 09:19
sorry i meant the latest version i.e 3.1.2

**Comment by narfbg** [comment] 2016-12-09 10:52
Please don't report multiple issues as one.

It makes it very hard to organize, and in this case - hard to analyze too ...

The "space issue" is a duplicate of #4902, which you also should've searched for.
And the other problem, I fixed now but it took significant time to weed out the relevant info for it, because you're mixing the two issues.

**Closed by narfbg** 2016-12-09 10:52 UTC

**Comment by newdriv** [comment] 2016-12-14 04:06
hi, I though specifying the two separate issues clearly would be good enough. But no worries will report them separately next time. When should I expect 3.13 for download
 thanks,
