### ISSUE TITLE
Can not use memcached to store session.

### ISSUE THREAD

**Issue by kekeones** [bcit-ci/CodeIgniter#4006] opened 2015-07-28 14:04 UTC
The file 'Session_memcached_driver.php', line 111,
$this->_memcached->getServerList()  Is empty.
PHP Version 5.4.41, memcached Version 2.2.0 .

**Comment by narfbg** [comment] 2015-07-28 14:18
The fact that it's empty doesn't mean nothing. That check may be superfluous, but surely not the cause of whatever problem you may be having.

Marking this as a duplicate of #3919.

**Closed by narfbg** 2015-07-28 14:18 UTC
Labels: Duplicate
