### ISSUE TITLE
Seem like Batch insert Doesn't work while having an inconsistent associative array

### ISSUE THREAD

**Issue by punitgajjar** [bcit-ci/CodeIgniter#6124] opened 2022-03-28 06:27 UTC
I had an array like this 
```
$data[] = array(
            'DRAWING_NO'=>123,
            'NO_PLANNING'=>321,

        );
$data[] = array(
            'DRAWING_NO'=>456,
            'NO_PLANNING'=>654,
            'ON_CREATE'=>date('Y-m-d H:i:s')
        );
```
        
        Then I tried the batch insert!
        
        `$this->db->insert_batch('tb_drawing_one', $data);`
        
        and was throwing an error!

**Comment by SachinBahukhandi** [comment] 2022-04-02 08:06
Can you post the error stacktrace?

**Comment by gxgpet** [comment] 2022-04-02 08:28
Duplicate of #5803, #5086, and possible others.

**Closed as completed by gxgpet** 2022-04-02 08:28 UTC
Labels: Duplicate
