### ISSUE TITLE
Deprecated When updating to php 7.4 on ci 3.1.11

### ISSUE THREAD

**Issue by qamarhafeez** [bcit-ci/CodeIgniter#6059] opened 2021-08-27 20:36 UTC
Deprecated: Array and string offset access syntax with curly braces is deprecated in /xyz/system/libraries/Profiler.php on line 108

Deprecated: Array and string offset access syntax with curly braces is deprecated in /xyz/public_html/system/libraries/Profiler.php on line 138

Deprecated: Array and string offset access syntax with curly braces is deprecated in /xyz/public_html/system/libraries/Profiler.php on line 557

**Comment by otengkwame** [comment] 2021-09-04 10:25
Please check the version again, everything seems to be working

**Comment by karthik-code** [comment] 2021-09-12 04:01
This error occurs when we have enabled profiler. Using version CI 3.1.11, PHP 7.4.3

**Comment by narfbg** [comment] 2021-09-14 11:11
Duplicate of #5879.

**Closed by narfbg** 2021-09-14 11:11 UTC
