### ISSUE TITLE
Typo in Loader Class

### ISSUE THREAD

**Issue by dalley** [bcit-ci/CodeIgniter#4981] opened 2017-01-13 16:02 UTC
There is a typo in the Loader.php class that is throwing errors once I upgraded to 3.1.3.

```
protected function _ci_prepare_view_vars($vars)
	{
		if ( ! is_array($vars))
		{
			$vars = is_object($vars)
				? get_object_vars($object)
				: array();
		}

		foreach (array_keys($vars) as $key)
		{
			if (strncmp($key, '_ci_', 4) === 0)
			{
				unset($vars[$key]);
			}
		}

		return $vars;
	}
```

`$object` is undefined and should be `$vars`

**Comment by narfbg** [comment] 2017-01-13 16:04
Duplicate of #4975.

**Closed by narfbg** 2017-01-13 16:04 UTC
Labels: Duplicate
