### ISSUE TITLE
Library config loading is... different

### ISSUE THREAD

**Issue by ByroRedux** [bcit-ci/CodeIgniter#4997] opened 2017-01-26 13:47 UTC
The Loader loads config files for libraries quite differently than the common config loading CI_Loader::config().

1. It does not merge config files. For the common config, you can have
`application/config/my_config.php`
`packages/package_1/config/my_config.php`
Any values in your package_1 config will overload the application config.

2. It uses the first config file it finds from the earliest added package path, because config paths are not "unshifted" when adding package paths.
E.g. if you want a custom library My_library with a config file, and you are using packages, you set it up like this
`packages/package_1/libraries/My_library.php`
`packages/package_1/config/my_library.php`
Then you can have additional packages which may want to overload the config with
`packages/package_2/config/my_library.php`
I expect the config file from `package_2` to be loaded, but instead it uses the one from `package_1`, while loading an overloaded library, model or helper will work as expected (the latest added package path has precedence).
A more common example:
If the application dir has a `form_validation.php` config, there's no way you can overload it in a package, because the application dir is the first package path.

A quick fix to get the expected loading order (without merging) is to reverse the config_paths before looking for the config file.
In `Loader.php` method `_ci_init_library` (current line 1216) I changed (in my overloaded loader lib)
`foreach ($config_component->_config_paths as $path)`
with
`foreach (array_reverse($config_component->_config_paths) as $path)`

**Comment by narfbg** [comment] 2017-01-26 13:59
I don't understand what you're talking about in point 1; please clarify.

Your expectations in point 2 are incorrect.

**Comment by ByroRedux** [comment] 2017-01-26 14:12
In Config::load(), there's no break or return in the foreach loop, so both files will be loaded with `$this->load->config('my_config')`
If you have in file `application/config/my_config.php`
```
$config['val'] = 'foo';
$config['val_2'] = 'bar';
```
and in file `packages/package_1/config/my_config.php`
```
$config['val'] = 'yoo';
```
you will end up with config_item('val') being 'yoo'. That is, the config values are merged while being added to the config. The lib loader doesn't do this.

Note taken re 2., you cannot and should not overload library config files in packages.

**Comment by narfbg** [comment] 2017-01-26 15:17
There's only APPPATH in `CI_Config::$_config_paths` ...
Anyway, as I said - 2 works as intended, so closing.

**Closed by narfbg** 2017-01-26 15:17 UTC
