### ISSUE TITLE
A PHP Error was encountered Severity: Warning  Message: fwrite(): SSL operation failed with code 1. OpenSSL Error messages: error:140D00CF:SSL routines:SSL_write:protocol is shutdown  Filename: libraries/Email.php  Line Number: 184

### ISSUE THREAD

**Issue by athiradevi** [bcit-ci/CodeIgniter#5609] opened 2018-09-28 06:54 UTC
A PHP Error was encountered
Severity: Warning

Message: fwrite(): SSL operation failed with code 1. OpenSSL Error messages: error:140D00CF:SSL routines:SSL_write:protocol is shutdown

Filename: libraries/Email.php

Line Number: 184

**Comment by narfbg** [comment] 2018-09-28 13:08
Duplicate of #3538.

**Closed by narfbg** 2018-09-28 13:08 UTC
Labels: Duplicate
