### ISSUE TITLE
Validation error message for 'matches' rule uses field name instead of 'human' name

### ISSUE THREAD

**Issue by paulcanning** [bcit-ci/CodeIgniter#4619] opened 2016-05-06 14:52 UTC
I have two fields for changing a password, with the following rules in my controller:

```
$this->form_validation->set_rules('new_password', 'New Password', '');
$this->form_validation->set_rules('confirm_new_password', 'Confirm New Password', 'matches[new_password]');
```

If there is a mismatch, the validation error message is:

> The Confirm New Password field does not match the new_password field.

I'm sure it never used to be like this?

I'm using CI 3 (can't seem to find a specific version number in the code anywhere)

**Comment by paulcanning** [comment] 2016-05-06 15:02
Testing again seems to be OK!

**Comment by narfbg** [comment] 2016-05-11 20:45
Duplicate of #4210.

**Closed by narfbg** 2016-05-11 20:45 UTC
Labels: Duplicate

**Comment by paulcanning** [comment] 2016-05-11 21:28
Slightly different as it's not failing, it's just not providing "human"  names. Did the fix in the mentioned issue fix it? If so, was it pushed?

**Comment by narfbg** [comment] 2016-05-11 21:41
> Slightly different as it's not failing, it's just not providing "human" names.

`set_rules()` calls that don't actually provide rules are *ignored* - that's what #4210 *describes* and that's what's going on here too, hence why it is a duplicate.

> Did the fix in the mentioned issue fix it?

This is NOT going to be "fixed", because it's not broken in the first place - empty rules are NOT a valid use case. At best, they are a hack that happened to work in the past.

The fix that you're referring to resolves a different problem - you would know that if you skimmed through the comments.

> If so, was it pushed?

If it wasn't pushed, how would you be able to see it? :)
