### ISSUE TITLE
Filter URI

### ISSUE THREAD

**Issue by aanbar** [bcit-ci/CodeIgniter#3612] opened 2015-02-21 12:01 UTC
The last commit to URI class made the filter practically useless.

I think the filter_uri shouldn't be getting the $str by reference & it should match against decoded version of $str for the sake of preventing a not allowed characters from being passed.

Aside from that, The location of which the filter uri is called isn't convenient, I think it should be moved to a lower area & have a hook or it should be called prior to executing a controller method (after constructor) this would allow overriding the permitted_uri_chars from constructor for certain method from within the constructor of the controller.

**Comment by narfbg** [comment] 2015-02-21 17:06
I partly shared your opinion prior to the #3593 discussion, but ... I believe you've followed it.

What do you expect me to do with this really?

**Comment by aanbar** [comment] 2015-02-22 11:12
Yes, I followed it entirely.

As I understand filter_uri should be able to manipulate a copy of the string without affecting the standards as it's a filtering function; that's why I talked about not sending the string by reference which mean when you're decoding the url, you're not affecting the original input (it's kept locally to the function). 

In the second part of this issue, I am explaining or suggesting that we could move the filter to a place where the permitted_uri_chars could be affected through a controller constructor which means one could alter the 'permitted_uri_chars' according to uri_sgement which gives more control to the user.

**Comment by narfbg** [comment] 2015-02-22 14:30
What's the point of manipulating the string if the result of that manipulation goes nowhere?

As for allowing 'permitted_uri_chars' to be changed on the fly ... no, if you ask me, no configuration should be changed during runtime.

**Comment by aanbar** [comment] 2015-02-22 19:39
We're manipulating it for the sake of matching only, the function as it stands doesn't return anything or modify anything (the string is sent by reference but no modification to the string is being done).
And you're still able to send encoded slashes & have them arrive to the function without being turned into segments.

As for the modification during run-time I think it's a desirable change so you only have to add the extra characters for one method.

**Comment by narfbg** [comment] 2015-02-23 06:28
> We're manipulating it for the sake of matching only, the function as it stands doesn't return anything or modify anything (the string is sent by reference but no modification to the string is being done).
> And you're still able to send encoded slashes & have them arrive to the function without being turned into segments.

Well, if it doesn't return or modify anything ... it also doesn't manipulate anything. So why do you want to change it? The fact that it accepts by reference is not an issue by itself.

> As for the modification during run-time I think it's a desirable change so you only have to add the extra characters for one method.

It's a global setting, that doesn't make sense.

**Comment by Ignasimg** [comment] 2015-02-26 05:54
As the other part involved in this discussion previously I just want to make my point again.

"for the sake of preventing a not allowed characters from being passed." this is not truth!!!

I mean... it's working as intended, if you tell the filter to filter some character it will disallow it.

Now the issue (I think) you have is the following: urls with characters that are automagically percent-encoded by the broswer (even if in the url address it still shows off as the real character).

Now since you are receiving such things I wonder what you want?
-Do not receive any of them?
-Receive only some?

If you don't want to receive any just remove % from the filter.
If you want to receive only some of them, on the controller urldecode and filter. (And this is not a new issue since in older CI versions it was exactly like that)

---

On the other side in #3593 last comment narfbg said "So at this point I'm thinking a configuration value that enables automatic URL-decoding for those who want it." back then I was going to criticize it but I couldn't find any good reason, so I don't really know why you didn't do it.

**Comment by narfbg** [comment] 2015-02-26 09:53
I decided against a separate setting for that, as it introduced a level of complexity that I'm not happy with for such an edge case. Setting the 'uri_protocol' to PATH_INFO can be used to achieve the same effect.

Anyway, with no further feedback on this, I'm closing it.

**Closed by narfbg** 2015-02-26 09:53 UTC
