### ISSUE TITLE
Replace_batch() function? and Insert_batch() error on large data.

### ISSUE THREAD

**Issue by zocheyado** [bcit-ci/CodeIgniter#4452] opened 2016-02-11 19:06 UTC
I noticed that there is no replace_batch() function in the docs, do people not use this often? I pull data from an API regularly and I want to update any new entries that come through the API, OR update existing rows (as the values change quite often). Right now I have been just doing a simple ->replace() in a loop...which is fine except it takes about 20 minutes with the amount of data I have. 

Insert_batch() for example is incredibly fast at inserting rows and I am looking for something similar in replace_batch(). Maybe I am thinking about this wrong but it seems like replace_batch() would be the most common.

As for my issue with insert_batch() it seems to be only inserting the first 100 regardless of how many there really are.

**Comment by narfbg** [comment] 2016-02-11 22:21
Duplicate of #1652.

**Closed by narfbg** 2016-02-11 22:21 UTC
Labels: Duplicate

**Comment by zocheyado** [comment] 2016-02-11 22:23
I did read that post first, the reason why I made this post is that you dismissed the idea in the last issue

> ce you've requested it - I'm sure you could, from your point of view. But apparently, so far it's only you that needs such a functionality and your reasoning so far is "Since there's insert_batch() and update_batch(), why no replace_batch()". That doesn't sound like a popular feature request. :)

And I was giving a use case in my example since I knew you were looking for one.

**Comment by narfbg** [comment] 2016-02-11 22:40
There is a (stupidly presented) use case given there already, although yours does make more sense. Either way, you should've commented there instead of opening a new issue.

But still, you're only the second person in 3+ years to request that feature and demand for it is another point that I've touched in that quote. Ultimately, it was closed because nobody was going to implement it anyway.  
I know I'm not going to, and while I wasn't directly opposed to the idea back then, I kind of am now ... REPLACE should be used with caution; it has some low-level caveats, it's not just a handy alias for DELETE + INSERT.

**Comment by zocheyado** [comment] 2016-02-11 22:51
Do you care if I implement it? I have never made a pull request but I would not mind doing this. Reading this [article](https://thomashunter.name/blog/mysql-replace-vs-insert-on-duplicate-key-update/) the second option is more what I am looking for and in-fact the default replace() function uses replace into when it should use on duplicate key. I did a rough test by appending ON DUPLICATE KEY UPDATE to the end of an insert_batch() and it worked perfectly, but I wouldn't mind adding it as an actual part of the framework if you are open.

**Comment by narfbg** [comment] 2016-02-11 23:06
You're mixing way too many suggestions at the same time; I now don't understand if you want to change `replace()`, add `replace_batch()` using `REPLACE`, add `replace_batch()` using `INSERT ... ON DUPLICATE KEY UPDATE` or change `insert_batch()` to use `ON DUPLICATE KEY UPDATE` ...

Only one of these is an option - adding `replace_batch()` to use `REPLACE`, but I'd doubt if you can pull it off for *all* drivers, which is a requirement for us and what made the OP in the other issue give up on trying.

**Comment by zocheyado** [comment] 2016-02-12 01:02
I guess what I was saying is that _something_ (new function insertUpdate() or whatever) should be using ON DUPLICATE KEY UPDATE, and ideally it would have a batch option. I personally see not a whole lot of use in a batch version of the current replace since it does not preserve primary keys.

**Comment by narfbg** [comment] 2016-02-12 11:07
That's a feature that only exists in MySQL and as I said - we don't accept these. Any new feature that we introduce in the DB classes must natively work for most drivers and eventually emulated for the few that wouldn't.

**Comment by zocheyado** [comment] 2016-02-12 15:18
Oh! I did not understand what you meant until just now, yes this is mySQL specific. Maybe I will just make a plugin for Mysql users.
