### ISSUE TITLE
escape_like_str a database bug feedback

### ISSUE THREAD

**Issue by yuchonghua** [bcit-ci/CodeIgniter#4541] opened 2016-03-17 09:56 UTC
$ Sql = 'LIKE "%' $ this-> db-> escape_like_str ( '_') '%.."';
Will generate
$ Sql = 'LIKE "% _%!"';
The need to '!' To ci phpfile \ system \ database \ DB_driver.php 338 rows '\\'
原文
$sql = 'LIKE "%'.$this->db->escape_like_str('_').'%"';会生成$sql = 'LIKE "%!_%"';需要把ci phpfile\system\database\DB_driver.php 的 338行的 '!'改为'\\'
![ci_bug](https://cloud.githubusercontent.com/assets/17898715/13842519/93047920-ec69-11e5-9ba6-9f85136b47bd.png)

**Comment by narfbg** [comment] 2016-03-17 10:00
Exact duplicate of #4540, which in turn is a duplicate of #4462.
If you continue opening these, I will continue closing them.

Also, we only use English around here.

**Closed by narfbg** 2016-03-17 10:00 UTC
Labels: Duplicate

**Comment by yuchonghua** [comment] 2016-03-17 10:08
I now how to do it
