### ISSUE TITLE
form_validation library load error PHP Version 7.3.19

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [bcit-ci/CodeIgniter#5975] opened 2020-07-09 08:27 UTC
Hello 

i am using ci3 with php 7.3.19 after login error getting about deprecated function idn_to_ascii

```
Severity: 8192

Message: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated

Filename: libraries/Form_validation.php
```

![Annotation 2020-07-09 135450](https://user-images.githubusercontent.com/35251001/87016032-cd0edc80-c1eb-11ea-9043-399f0b41c448.png)

**Comment by narfbg** [comment] 2020-07-09 09:11
Duplicate of #5300.

**Closed by narfbg** 2020-07-09 09:11 UTC
