### ISSUE TITLE
url_title() don't handel special letters

### ISSUE THREAD

**Issue by FromeXo** [bcit-ci/CodeIgniter#5306] opened 2017-10-19 22:24 UTC
On Swedish sites and i guess in equal countries with special letters like Å. Ä and Ö it should be replaced with A, A and O

Suggestions is to also translate other letters like ß to ss and ü to u.

**Comment by narfbg** [comment] 2017-10-20 09:18
Duplicate of #1332.

**Closed by narfbg** 2017-10-20 09:18 UTC
Labels: Duplicate
