### ISSUE TITLE
Encrypt library 

### ISSUE THREAD

**Issue by mahendravikhar** [bcit-ci/CodeIgniter#5476] opened 2018-04-19 06:40 UTC
The Encrypt Library is still using mcrypt extension. How we can use this on PHP 7.1.11

URL: https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Encrypt.php

`public function __construct()
	{
		if (($this->_mcrypt_exists = function_exists('mcrypt_encrypt')) === FALSE)
		{
			show_error('The Encrypt library requires the Mcrypt extension.');
		}
		log_message('info', 'Encrypt Class Initialized');
	}`

**Comment by narfbg** [comment] 2018-04-19 08:48
Duplicate of #5054.

**Closed by narfbg** 2018-04-19 08:48 UTC
