### ISSUE TITLE
system\helpers\form_helper.php 3.0.4

### ISSUE THREAD

**Issue by mauroconde** [bcit-ci/CodeIgniter#4456] opened 2016-02-12 12:45 UTC
Line 794   return ($input === 'value') ? ' checked="checked"' : '';
Line 794 should be? return ($input === $value) ? ' checked="checked"' : '';

Line 847  return ($input === 'value') ? ' checked="checked"' : '';
Line 847  should be? return ($input === $value) ? ' checked="checked"' : '';

**Comment by narfbg** [comment] 2016-02-12 12:48
Duplicate of #4426.

**Closed by narfbg** 2016-02-12 12:48 UTC
Labels: Duplicate
