### ISSUE TITLE
Form_validation always accepts empty array 

### ISSUE THREAD

**Issue by Bitblade** [bcit-ci/CodeIgniter#4516] opened 2016-03-11 19:33 UTC
See the following code:

````php
		$this->load->library('form_validation');
		
		$inputData = ['inp' => []];
		$this->form_validation->set_data($inputData);
		
		$this->form_validation->set_rules('inp', 'Input field', 'is_natural|required');
		
		//Will return true
		$this->form_validation->run();
````

This behaviour seems to be caused by a missing check in the following code:
````php
	protected function _execute($row, $rules, $postdata = NULL, $cycles = 0)
	{
		// If the $_POST data is an array we will run a recursive call
		if (is_array($postdata))
		{
			foreach ($postdata as $key => $val)
			{
				$this->_execute($row, $rules, $val, $key);
			}

			return;
		}
````

**Comment by narfbg** [comment] 2016-03-11 19:56
There's no missing check.

An empty array means no data, which in turn means no form was submitted - the library doesn't "accept" it; it *ignores* it. That's the intended behavior.

**Comment by Bitblade** [comment] 2016-03-11 20:02
Forgive me, but either I did not explain my problem well enough, or I have to reread the manual again. 

Another example: 
Two input fields, both required and `is_natural

**Comment by Bitblade** [comment] 2016-03-11 20:05
Forgive me, but either I did not explain my problem well enough, or I have to reread the manual again. 

Another example: 
Two input fields, both `required` and `is_natural`

The input is accepted (`$this->form_validation->run()` returns true) even though the second value is an empty array instead of the required natural number. 

````php
		$this->load->library('form_validation');
		
		$inputData = ['number1' => 5, 'number2' => []];
		$this->form_validation->set_data($inputData);
		
		$this->form_validation->set_rules('number1', 'Input field 1', 'is_natural|required');
		$this->form_validation->set_rules('number2', 'Input field 2', 'is_natural|required');
		
		//Will return true
		$this->form_validation->run();
````

**Comment by narfbg** [comment] 2016-03-11 20:21
Hmm ... I didn't notice the 'inp' key in your initial post, my bad.

**Comment by narfbg** [comment] 2016-03-11 20:36
Confirmed ... too bad you didn't report this a few hours earlier, the fix could've landed into 3.0.5. :/

**Comment by narfbg** [comment] 2016-03-11 20:40
Also, incidentally, this will provide progress towards #193.

**Closed** 2016-03-12 09:41 UTC
Labels: Bug, Critical

**Comment by narfbg** [comment] 2016-03-12 13:15
I'll try to release 3.0.6 ASAP (next week), this is pretty bad.

**Comment by coldlamper** [comment] 2016-04-05 20:38
Won't this return true as well if you use inp[] in the rule even in the 3.0.6 release? Does for me.
        
        $this->load->library('form_validation');
        $inputData = ['inp' => []];
        $this->form_validation->set_data($inputData);

        $this->form_validation->set_rules('inp[]', 'Input field', 'is_natural|required');

        //Will return true
        $this->form_validation->run();

Also how do you post an empty array? Is this fix only relevant when using $this->form_validation->set_data?

**Comment by narfbg** [comment] 2016-04-06 07:29
'inp[]' is not the same as 'inp'; please post on our [forums](http://forum.codeigniter.com/) if you don't understand how it works.
