### ISSUE TITLE
Validation rules deiniftion

### ISSUE THREAD

**Issue by neomicho85** [bcit-ci/CodeIgniter#4586] opened 2016-04-18 02:16 UTC
when i write
required|is_unique[categories.category] 
with no spaces between the tube everything is ok, but when i write
required | is_unique[categories.category]
with spaces between the tube there is an error. I think you should trim after split the validation rules.

**Comment by narfbg** [comment] 2016-04-18 07:40
Duplicate of #3247.

**Closed by narfbg** 2016-04-18 07:40 UTC
Labels: Duplicate
