### ISSUE TITLE
_ci_prepare_view_vars typo?

### ISSUE THREAD

**Issue by ajorias** [bcit-ci/CodeIgniter#5048] opened 2017-03-08 22:53 UTC
I guess get_object_vars($object) should be get_object_vars($vars) ?

	protected function _ci_prepare_view_vars($vars)
	{
		if ( ! is_array($vars))
		{
			$vars = is_object($vars)
				? get_object_vars($object)
				: array();
		}

**Comment by narfbg** [comment] 2017-03-08 23:36
Duplicate of #4975.

Please use the search bar before opening new issues.

**Closed by narfbg** 2017-03-08 23:36 UTC

**Comment by DJRENAN** [comment] 2017-03-24 02:14
Alexander, i'm a club player cooee and youtuber,
I took mt to get in touch with you, I was wondering if you can do a short interview for my cooee club channel.
All cooee club players in brazil want something more than a sign of your visa, please.

My channel on YouTube is called IMPERIO GAMER PLAY.
Thanks for listening.
And I'm sorry I'm translating this because I'm Brazilian and I speak Portuguese.
