### ISSUE TITLE
set_value default not working as expected

### ISSUE THREAD

**Issue by jamieburchell** [bcit-ci/CodeIgniter#3905] opened 2015-06-11 17:14 UTC
Latest CI3 release.

The `name` from `object` is used as the field value when submitting an empty value. If you submit an empty value, the field should be empty and not use the default.

`<?php echo set_value('name', $object->name);`

**Comment by narfbg** [comment] 2015-06-15 15:14
Duplicate of #3816.

**Closed by narfbg** 2015-06-15 15:14 UTC
