### ISSUE TITLE
email attachment not downloadable

### ISSUE THREAD

**Issue by sargac** [bcit-ci/CodeIgniter#4817] opened 2016-09-21 20:33 UTC
Hi!

Using CI 3.1.0 I've noticed the attachment is not downloadable. It appears in an email client software, but there is a missing filesize and it is not possible to open it. After examining the message code, I've noticed the difference from other messages with working attachments, and that was a missing newline between the attachment headers and base64 content. As soon as I added a newline character to Email system library, attachment started to working correctly, so please examine this, and apply a patch where appropriate.

The issue with a solution is available here as well
http://stackoverflow.com/questions/25416585/codeigniter-send-email-with-attach-file

Temporary fix (or maybe a final as well?) is the following. At line 725 of Email, function *attach()*, there should be a "\r\n" newline character, as displayed below:

```php
# system/libraries/Email.php, line 725
'content'	=> "\r\n" . chunk_split(base64_encode($file_content)),
```

Best!

**Comment by narfbg** [comment] 2016-09-21 20:42
Duplicate of #4739.

**Closed by narfbg** 2016-09-21 20:42 UTC
Labels: Duplicate
