### ISSUE TITLE
An Error Was Encountered

### ISSUE THREAD

**Issue by scgywx** [bcit-ci/CodeIgniter#4248] opened 2015-11-17 09:24 UTC
if enable_query_strings is TRUE, Router initialize was failed, because Router::$default_controller is empty.
so open index.php will got an error, message is "Unable to determine what should be displayed. A default route has not been specified in the routing file".

my means add follows code before $this->_set_routing() in Router.php
$this->default_controller = $this->config->item('default_controller');

and add follows code in config/config.php
$config['default_controller'] = 'my_default_controller';

**Comment by narfbg** [comment] 2015-11-17 09:51
Duplicate of #4109.

**Closed by narfbg** 2015-11-17 09:51 UTC

**Comment by scgywx** [comment] 2015-11-18 06:11
u are right, but if enable_query_strings is TRUE, this routes.php don't need to be loaded.
:)
