### ISSUE TITLE
phpversion('phpredis') and redis->sRemove issues

### ISSUE THREAD

**Issue by nickimnick** [bcit-ci/CodeIgniter#5860] opened 2019-10-20 09:17 UTC
After 3.1.11 upgrade, still, have some issues about Redis driver. I am using PHP 7.0.33-11 and Redis 5.0.2 on Ubuntu 16.04.1

In [https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Cache/drivers/Cache_redis.php](url) file at line 101 there is a small code which is trying to get the version of phpredis and then setting the function name to "delete" or "del".

`phpversion('phpredis') `

This part is always returning false. Because It's can't get the version of phpredis extension with this string 'phpredis'. At least, It is happening in my environment. It's working fine with 'redis'.

The function named "delete" is not the only function removed from phpredis. "sRemove" we have to use "sRem" instead. And this is being used at line 213 and 234.

**Comment by narfbg** [comment] 2019-10-21 08:03
Duplicate of #5846.

Also, on the `sRemove` vs `sRem` - you're looking at a branch that doesn't have the corresponding patch(es) merged yet, but we do already handle that issue.

**Closed by narfbg** 2019-10-21 08:03 UTC
