### ISSUE TITLE
CI 3 When uri_protocol = QUERY_STRING and enable_query_strings = TRUE , $route['default_controller'] is not processed in the system/core/Router.php in QUERY_STRING mode

### ISSUE THREAD

**Issue by tayfund** [bcit-ci/CodeIgniter#4479] opened 2016-02-22 20:42 UTC
Hello,
When **uri_protocol = QUERY_STRING** and **enable_query_strings = TRUE** , the **$route['default_controller']**  is not processed in the _system/core/Router.php_
Because before **include(APPPATH.'config/routes.php')** and _class default_controller variable_ is not set, **$this->_set_default_controller()** function called. So class does not see the default controller and gives error.

**Comment by narfbg** [comment] 2016-02-22 21:28
Duplicate of #4109.

Just 2 hours ago I closed [another duplicate issue](https://github.com/bcit-ci/CodeIgniter/issues/4478) for something that was fixed in 3.0.2. What's up with that?

**Closed by narfbg** 2016-02-22 21:28 UTC
