### ISSUE TITLE
Unsanitized User Input - /system/libraries/Upload.php

### ISSUE THREAD

**Issue by Alexalas** [bcit-ci/CodeIgniter#5344] opened 2017-11-29 15:47 UTC
The name of the file "0[name]" is received in method CI_Upload::do_upload() in line 379 of example/system/libraries/Upload.php.

It is concatenated into path markup in function do_upload() in line 566 of example/system/libraries/Upload.php.

The user-supplied data is then used unsanitized in the sensitive operation copy() in method CI_Upload::do_upload() in line 566 of example/system/libraries/Upload.php.

374	class CI_Upload
{
public function do_upload($field = 'userfile')
{

379	$_file = $_FILES[$field];

384	$_file = $_FILES;

390	$_file = NULL;

394	$_file = $_file[$field];

566	copy($this->file_temp, $this->upload_path . $this->file_name);

**Comment by narfbg** [comment] 2017-11-29 16:02
Duplicate of #5343.

**Closed by narfbg** 2017-11-29 16:02 UTC
Labels: Duplicate
