### ISSUE TITLE
bypassing locks?

### ISSUE THREAD

**Issue by Ignasimg** [bcit-ci/CodeIgniter#3627] opened 2015-02-26 05:09 UTC
Ok before someone  jumps to say I'm wrong, and this is not a bug or whatever, I want to make clear I have no fucking idea if it's intended to do what it should or not, I didn't even try them, but those locks really look suspicious... so... yes it's not a bug (at least yet) just suspicious code.

So I was taking a look at the session_redis_driver and session_memcached_driver when I noticed something... weird.

The relevant part of the code is the _get_lock() function on both drivers, what they do is something similar to that:
```PHP
protected function _get_lock($session_id)
	{
		if (isset($this->_lock_key))
		{
			return $this->_memcached->replace($this->_lock_key, time(), 5); // memcached
			return $this->_redis->setTimeout($this->_lock_key, 5); // redis
		}

		// [code #1 to try to aquire the lock]
		// If it succeeds set _lock_key and return true
		// If it didn't succeed (the lock is taken) continue

		// [code #2 to try to aquire the lock]
                // Try #2 a few times and if success do something similar to 1 (particullary set _lock_key)
		// If it didn't succeed for those few times fail.
	}
```

And the possible break is: At time 0, we receive the first request, the database is empty so it just aquires the lock from code#1 and returns, but let's imagine this request, is a big computing that will take exactly 7 seconds.

Now at time 3, we receive another request (while the other process is still computing the past request), there's still the lock in the database so we execute code#2 for around 2 seconds, and finally receive the lock. 

At time 7, the first request, finishes the computing and decides to store it on session cause it's convinient...
so it goes to the _get_lock function and since this process had already accessed the session before, he already has the _lock_key "set" enters the if and bam... now both request have access to the session...

Ok, now I admit I don't know really good (in fact not at all) the redis and memcached drivers, and also don't know if this is solved behind the scenes with something weird as clearing _lock_key every 5 seconds or so, but to me it looks bugful. (Or maybe I missed something, in which case a simple explanation would make the deal)

**Comment by kakysha** [comment] 2015-02-26 09:18
How do you suppose to acquire the lock from second request at time 3+2 if it is already taken by the first one?

**Comment by narfbg** [comment] 2015-02-26 09:50
Confirmed, although the Redis and Memcached drivers are built around the assumption that you need their speed, and therefore you should never have a request that takes more than 5 seconds to process.

**Comment by Ignasimg** [comment] 2015-02-26 19:54
No ofense but I think this assumption is at most... useless.

What I mean is who doesn't want their website to be as fast as possible?

But this doesn't mean, we always can return requests before 5 (or just X) seconds...
It might be cause the request need to do something weird with data or because you need to request something from other servers, and you know from time to time the network and/or the server will be more busy and you'll take X+1 seconds. Shit happens...

Well that being said, I have searched and documented myself to try to propose a working solution for both of them, and aparently in redis is not only easy, but already done (even with distributed back-end) [redlock](http://redis.io/topics/distlock#distributed-locks-with-redis), however in memcached not only there isn't anything similar to it, but also seems impossible in the terms redis does it (it's possible to make an atomic operation such as [Memcached::add](http://php.net/manual/en/memcached.add.php)) but it's not possible to delete a key with a condition of the value (atomically). Nevertheless I still think it's possible to do it on memcache (in other terms as I said, but possible...)

Now I know what will you say "those algorithms are too big", and I agree with you, and I'll also add "they only solve some edge cases, that are also relatively hard to happen" (in my opinion, even without the locks it's hard to have an issue with it)

But if we don't change those algorithms AT THE VERY LEAST it should be noted in the documentation somehow that a requests should only access session within the first five seconds of the requests (trying to don't run into missunderstandings by people thinking they need to check the time before accessing session...) And after all... honestly I think it would be quite hilarious... so in my opinion we should change the _lock procedures, to achieve a real lock. What do you think about it?

**Comment by narfbg** [comment] 2015-02-26 20:08
A quote from the docs:

> Since Redis doesn't have a locking mechanism exposed, locks for this driver are emulated by a separate value that is kept for up to 5 seconds. You may experience issues if your page loads take longer than that!

Seriously though, me saying "Confirmed" meant that this is a bug that must be fixed. The 5 second timeout should only cause subsequent requests to fail, not the first to obtain the lock.

I'm inclined to disagree with everything else you said/proposed, but it's not worth discussing it ... you shouldn't have either.

**Comment by Ignasimg** [comment] 2015-02-26 20:30
Sorry, I checked the docs on the web, not the ones in the git.

And I'd really like to know why you disagree on the proposals, not to start a flame war, but I'd like to help with some implementation that really works. (Am I right if I guess the good version shouldn't have anything to do with times? While hopefully being dead-lock free?)

**Comment by narfbg** [comment] 2015-02-26 21:06
> No ofense but I think this assumption is at most... useless.
>
> What I mean is who doesn't want their website to be as fast as possible?

 - Use Redis/Memcached sessions for *speed*.
 - Have *concurrent* page-loads taking *more than 5 seconds to complete* and *without closing the session first*.

... that's useless. I'm sure you understand why.

> But this doesn't mean, we always can return requests before 5 (or just X) seconds...

If you can't, something's wrong with your application.

> It might be cause the request need to do something weird with data or because you need to request something from other servers, and you know from time to time the network and/or the server will be more busy and you'll take X+1 seconds. Shit happens...

Anytime you use an external resource, you'll lose any performance benefit that you've gained from using Redis or Memcached. Therefore, you're just as good using the 'files' driver, which isn't the default for no reason ...

> Well that being said, I have searched and documented myself to try to propose a working solution for both of them, and aparently in redis is not only easy, but already done (even with distributed back-end) redlock, however in memcached not only there isn't anything similar to it, but also seems impossible in the terms redis does it (it's possible to make an atomic operation such as Memcached::add) but it's not possible to delete a key with a condition of the value (atomically). Nevertheless I still think it's possible to do it on memcache (in other terms as I said, but possible...)

You can't have a deadlock-free mechanism without time values. Even redlock uses them.

> Now I know what will you say "those algorithms are too big", and I agree with you, and I'll also add "they only solve some edge cases, that are also relatively hard to happen" (in my opinion, even without the locks it's hard to have an issue with it)

Yep, not worth it ... even if I didn't have anything other against them.

> But if we don't change those algorithms AT THE VERY LEAST it should be noted in the documentation somehow that a requests should only access session within the first five seconds of the requests (trying to don't run into missunderstandings by people thinking they need to check the time before accessing session...) And after all... honestly I think it would be quite hilarious... so in my opinion we should change the _lock procedures, to achieve a real lock. What do you think about it?

I believe I already answered that with my previous comment. Except there's no such thing as a "real lock" on these platforms, you can only emulate a lock.

-----------------

> Am I right if I guess the good version shouldn't have anything to do with times? While hopefully being dead-lock free?

No, read above.

**Comment by Ignasimg** [comment] 2015-03-01 05:45
Ok, I don't agree with you on the first points, and a quick example comes to my mind... (an airplane ticket search engine, that stores the results on session) but as you said and I agree that's a worthless discussion... now to the issue.

Is there a way to avoid deadlocks without time values? Definely not when the process might ask for different locks, but I certainly think there is in our case, which a process might want at most 1 lock at a time... Altought it's far from simple to implement, one could store a server_id & process_id of the current process who has the lock. The next process getting stoped by the lock should send a request to the server asking if the process is still alive... if the process is still alive it's mean sooner or later it will release the lock (unless it's trapped on something else, but that's not the lock problem...), on the other side if the process is not alive, the process which wants the lock should create a new sessionid, somehow based in a deterministic way on the one that's "locked" and create a new lock with this new sessionid... and yet it'd produce some issues like having the database with zombie locks... which I guess could also be solved by some weird process also without time... but yes... I deffinely think even this is possible it's not the way to go...

So now my other proposal which is far more simple... what if we allow deadlocks? As said before, in our case deadlocks only occur when a process either dies without clearing the lock, or it's trapped on an infinite loop.
Now... how much infinite is the infinite? yep that might sound funny, but in php if you want to have an infinite loop which last longer than 30 seconds, you deliverately need to do it... it's not a matter of having a bug...
Having said that, it wouldn't be hard to setup a [shutdown function](http://php.net/manual/en/function.register-shutdown-function.php) that releases the session lock on shutdown, so the case of incidental infinite loop I think is solved quite gracefully.

So what if the process dies? (without executing the shutdown function) or if the server lost the connection at the time to release the lock? We're in deadlock. And we'll fuck up the user experience by asking them to logout / login again. That's deffinely not good.

But what about a dead-lock free version with TTL? well at some point if you are "lucky" enough, you might find yourself with weird issues, hard to replicate, etc...

So the question is.... what is most likely to happen? 
That two or more requests get lucky to fall in love with each other and end up making love with your session data.
Or that a server / process misteriously dies or loses connection.

That's also something we could discuss about for a long time without getting nowhere, but my point is a non-deadlock free solution should at least be considered.

---

Extra note: 
While writting this I happened to think about another solution, similar to the deadlock free proposed above, but instead of keeping the server_id / process_id on the lock, you can keep [connection_id](http://redis.io/commands/client-getname) in redis. And not only that, but once a new process wants the lock, it doesn't need to check a remote server, redis itself could [check](http://redis.io/commands/client-list) if the connection died, and if so erase the lock. Still a little bit hardlifting but much more clean I think. The downside is it would only work on redis...

Anyway just some thoughts

**Comment by narfbg** [comment] 2015-03-04 09:32
> Is there a way to avoid deadlocks without time values? Definely not when the process might ask for different locks, but I certainly think there is in our case, which a process might want at most 1 lock at a time... Altought it's far from simple to implement, one could store a server_id & process_id of the current process who has the lock. The next process getting stoped by the lock should send a request to the server asking if the process is still alive... if the process is still alive it's mean sooner or later it will release the lock (unless it's trapped on something else, but that's not the lock problem...), on the other side if the process is not alive, the process which wants the lock should create a new sessionid, somehow based in a deterministic way on the one that's "locked" and create a new lock with this new sessionid... and yet it'd produce some issues like having the database with zombie locks... which I guess could also be solved by some weird process also without time... but yes... I deffinely think even this is possible it's not the way to go...

Just FYI, there are two flaws in that scheme, even ignoring the sheer complexity that makes it impractical:

 - Generating a new session ID is not an option.
 - Running this on any httpd with multi-thread execution model may result in two concurrent requests with the same process ID.

> So now my other proposal which is far more simple... what if we allow deadlocks? As said before, in our case deadlocks only occur when a process either dies without clearing the lock, or it's trapped on an infinite loop.
Now... how much infinite is the infinite? yep that might sound funny, but in php if you want to have an infinite loop which last longer than 30 seconds, you deliverately need to do it... it's not a matter of having a bug...
Having said that, it wouldn't be hard to setup a shutdown function that releases the session lock on shutdown, so the case of incidental infinite loop I think is solved quite gracefully.

You lost me at "allow deadlocks", that's a debugging nightmare far worse than anything else that we're trying to solve, especially in a web application.

Also, `session_write_close()` is already registered as a shutdown function and it does free the lock, but again - if the request crashes for whatever reason, we're doomed.

> So what if the process dies? (without executing the shutdown function) or if the server lost the connection at the time to release the lock? We're in deadlock. And we'll fuck up the user experience by asking them to logout / login again. That's deffinely not good.

A deadlock condition means you can't acquire the lock, the request times out and you can't even offer the option to logout. The user will have to stop visiting the page until the whole session is expired.

> But what about a dead-lock free version with TTL? well at some point if you are "lucky" enough, you might find yourself with weird issues, hard to replicate, etc...

The only problem with TTLs is having the right timings. You found a *timing* flaw in the current scheme and that's what we need to fix ... I believe I've got the solution already and will try to commit it today.

> So the question is.... what is most likely to happen?
That two or more requests get lucky to fall in love with each other and end up making love with your session data.
Or that a server / process misteriously dies or loses connection.
>
> That's also something we could discuss about for a long time without getting nowhere, but my point is a non-deadlock free solution should at least be considered.

Yeah ... no. :)
Read above.

> Extra note:
While writting this I happened to think about another solution, similar to the deadlock free proposed above, but instead of keeping the server_id / process_id on the lock, you can keep connection_id in redis. And not only that, but once a new process wants the lock, it doesn't need to check a remote server, redis itself could check if the connection died, and if so erase the lock. Still a little bit hardlifting but much more clean I think. The downside is it would only work on redis...

Neat, but yes - too much hardlifting and downsides.

**Closed** 2015-03-04 11:33 UTC

**Comment by Ignasimg** [comment] 2015-03-05 11:28
Well even I don't fully understand your objections about the first solution I proposed, since (I think) we both think second one was the best solution (even though only working on redis), yet you don't seem to like it much, let's leave this discussion here.

On the other side... either you or me didn't understand anything...
You say I found a timing flaw? What do you exactly mean by that? You mean the problem was that the lock would only be held for 5 seconds while an http timeout usually happens at 300 seconds?
Maybe that is part of the problem, but in my opinion, the real problem, (even though now whit such a big TTL will probably never appear) is still there.

And finally you say allowing deathlocks would be a debugging nightmare... And you got a point, about the logout thing (even though it can be solved by ... ugly dirty and nasty solutions).
But since the problems that could lead to a deathlock (if we allowed them) would also lead to a 5 minutes deathlock in the current version... I ask you, isn't 5 minutes a debugging nightmare?

**Comment by narfbg** [comment] 2015-03-05 12:02
> On the other side... either you or me didn't understand anything...
You say I found a timing flaw? What do you exactly mean by that? You mean the problem was that the lock would only be held for 5 seconds while an http timeout usually happens at 300 seconds?
Maybe that is part of the problem, but in my opinion, the real problem, (even though now with such a big TTL will probably never appear) is still there.

What do you mean what do I mean? Request1's lock may timeout before the request is actually completed, allowing Request2 to "take over" - you explained this in your issue description. This is the *only* problem and it no longer exists.

> And finally you say allowing deathlocks would be a debugging nightmare... And you got a point, about the logout thing (even though it can be solved by ... ugly dirty and nasty solutions).
But since the problems that could lead to a deathlock (if we allowed them) would also lead to a 5 minutes deathlock in the current version... I ask you, isn't 5 minutes a debugging nightmare?

A deadlock doesn't timeout after 5 minutes, it's unbreakable and therefore infinite - that's why it's called a deadlock. 5 minutes is a relatively long time to block a session, but still way better than holding it until the session expires.

--------------

As much as I enjoy discussing in-depth technical problems, can we stop this now? No offense but you talk a little bit too much and I'm trying very hard to prevent the issue tracker from turning into a forum board. :)
