### ISSUE TITLE
Form helper for type number in CodeIgniter 3.x.

### ISSUE THREAD

**Issue by satyakresna** [bcit-ci/CodeIgniter#4673] opened 2016-06-21 11:55 UTC
Hi, Thanks for reading this issues. I have type `form_input()` for my form which type is number. This is my code:

`<?php
                $extra = array(
                                'type' => 'number',
                                'id' => 'nilai',
                                'class' => 'form-control',
                                'placeholder' => 'Nilai',
                                'required' => 'required'
                );
                echo form_input('nilai', set_value('nilai'), $extra);
            ?>`

After I run in my browser, if I type character alphabet, this form can do it. I'm curios. So, I inspect element (I'm using Google Chrome Browser). The screenshot show that the type of form is "text" not  "number".
![request form_number](https://cloud.githubusercontent.com/assets/11099186/16228328/f9afed4c-37e8-11e6-9325-bbd56015fff8.PNG)

I have read CodeIgniter documentation about form_helper. I search that there's no `form_number` helper.
Honestly, I can use the html syntax for fix this problem like
`<input type="name" name="nilai" value="" id="nilai" class="form-control" placeholder="Nilai" required="required">`. But, I like the form_helper syntax of CodeIgniter provide. So, can I request for form number for CodeIgniter next version? Or, maybe you and team can combine `form_hidden()`, `form_password()` to `form_input()` . Thank you very much.

**Comment by narfbg** [comment] 2016-06-21 12:02
Duplicate of #1448.

**Closed by narfbg** 2016-06-21 12:02 UTC
Labels: Duplicate

**Comment by satyakresna** [comment] 2016-06-21 13:00
Thank you very much @narfbg for show reference. I have also ask the groups and found solutions to combine code like this:
`<?php
                $extra = array(
                                'type' => 'number',
                                'name' => 'nilai',
                                'value' => set_value('nilai'),
                                'id' => 'nilai',
                                'class' => 'form-control',
                                'placeholder' => 'Nilai',
                                'required' => 'required'
                );
                echo form_input($extra);
            ?>`

**Comment by narfbg** [comment] 2016-06-21 13:02
Please note that this is a bug tracker, not a "solutions" place.
Post on our [forums](http://forum.codeigniter.com/) instead.
