### ISSUE TITLE
In the db query builder for mysql, the where_in method silently does not include the 'where in' clause when passed NULL as a value

### ISSUE THREAD

**Issue by derekyle** [bcit-ci/CodeIgniter#5631] opened 2018-11-06 02:10 UTC
This seems like undesirable behavior. Logically, one would think that this:

$this->db->where_in('some_column',NULL);
$this->db->update('test_table',['other_column'=>'hello']);

Would build a query like: 

UPDATE test_table SET test_column='hello' WHERE some_column IN (NULL);

But it actually is much more dangerous:

UPDATE test_table SET test_column='hello';

Thus updating every record in the database rather than those that match the WHERE IN clause.

Tested in version 3.1-stable

**Comment by narfbg** [comment] 2018-11-16 14:42
`some_column IN (NULL)` would match nothing (as in, even NULL values wouldn't match), so this is just plain incorrect usage ...

**Comment by derekyle** [comment] 2018-11-16 17:38
Yes, it's incorrect usage, but is a conceivably common error that should
throw an error. Silently ignoring and thus overwriting every record in
someone's table is a terrible idea.

**Comment by narfbg** [comment] 2018-11-20 16:55
A conceivably possible mistake to make? Sure, if you have some complex criteria-collecting logic, maybe some sloppy programming would allow an `array(NULL)` to pass through where it shouldn't, and one of those times it will happen to go into a `where_in()` call while there's no other criteria. But I could never see this as anything close to common.  

What I'm saying is that's a weak argument, especially as a fallback to your original issue description. But I do agree that an accidental table wipe-out is a terrible outcome regardless of what lead to it. Do you have a patch proposal?

**Comment by derekyle** [comment] 2018-12-15 09:57
Regardless of how common or not it might be to get a NULL passed into a where_in clause, just silently dropping the where_in is a terrible idea. As for the solution, you said it yourself:

> some_column IN (NULL) would match nothing

so if a NULL value is passed it should match nothing - not potentially everything as it does now.

**Comment by narfbg** [comment] 2018-12-17 07:54
> a terrible idea

You're saying that for the second time, and as if the entire thing is intentionally designed to behave this way. It's an unintended side-effect, occurring only with incorrect usage and I already agreed that it should be dealt with ... why are you still arguing?

> I believe in mysql at least, WHERE IN (NULL) will throw an error

Nope, it executes without even a warning.

**Comment by derekyle** [comment] 2018-12-18 04:40
I'm not arguing. You asked if I had a patch proposal.

I'm proposing that where_in('field',NULL) should generate a WHERE field IN (NULL)

**Comment by narfbg** [comment] 2019-01-02 00:06
OK, it's been crystal clear from the beginning that this is what you're suggesting. But when I say *patch* proposal I mean an actual patch ...

Also, the issue is still unresolved, so it shouldn't be closed.

**Comment by derekyle** [comment] 2019-01-03 05:48
#5668 Ok, this would be my proposal. All I did was remove the function that is checking if a NULL value is passed. This will allow a NULL value to get through to the WHERE IN portion of the query.

**Comment by almatins** [comment] 2019-01-14 03:39
try this,
$where = 'some_column is null';
$this->db->where($where);

**Comment by narfbg** [comment] 2019-01-15 10:46
@almatins This is a bug tracker, not a place to post random suggestions.

**Comment by narfbg** [comment] 2019-02-14 17:28
Incidentally, this is resolved by the solution for #4186.

**Closed by narfbg** 2019-02-14 17:28 UTC
