### ISSUE TITLE
Codeigniter Backup Restore Error

### ISSUE THREAD

**Issue by sanjayacloud** [bcit-ci/CodeIgniter#5472] opened 2018-04-17 11:36 UTC
Hello,
I have create a database backup using codeigniter $this->load->dbutil(); This Work fine and I can download my database backup. But I try to restore this backup and I got below error..

SQL query:

INSERT INTO `app_user` (`id`, `user_name`, `email`, `password`, `role`, `status`) VALUES (10, Admin.sgh, admin@supreme.lk, 202cb962ac59075b964b07152d234b70, 0, 0)
MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@supreme.lk, 202cb962ac59075b964b07152d234b70, 0, 0)' at line 1

**Can you help me to resolve this error. I am using codeigniter  3.1.6 Version..**

**Comment by narfbg** [comment] 2018-04-18 09:03
Duplicate of #5276.

**Closed by narfbg** 2018-04-18 09:03 UTC
