### ISSUE TITLE
Uploading multiple images using upload library

### ISSUE THREAD

**Issue by eloyucu** [bcit-ci/CodeIgniter#4915] opened 2016-11-18 16:51 UTC
I am trying to upload many different files using the codeigniter. This is a little snippet of my code:
HTML

`<input type="file" name="element[img][]">`

PHP

`$this->ci->upload->do_upload("element")` 

And, I get this error:
 
    A PHP Error was encountered  
    Severity: Warning  
    Message: is_uploaded_file() expects parameter 1 to be string, array given  
    Filename: libraries/Upload.php  
    Line Number: 412  

Is there any "official" way to upload an array of images (or any other file), or do I need modify manually the upload library to make it possible. 

Thank you. 

PS: I had tried too using `$this->ci->upload->do_upload("element[img][$index]")`, but I get another error (You did not select a file to upload.).

**Comment by narfbg** [comment] 2016-11-18 17:56
Duplicate of #173. Please use the search bar.

Also, this is a bug tracker. Unless you have a bug to report, please post on our [forums](http://forum.codeigniter.com/) instead.

**Closed by narfbg** 2016-11-18 17:56 UTC

**Comment by eloyucu** [comment] 2016-11-20 17:38
Ok!! I only ask about if there was an normalized way to do that. How I see there isn't this functionallity and you will not fix it, I make my own function (by the moment, for img it works)

	//In the Upload system library
	private function normalizeImageFromArray($_file, $index)
	{
		$result = array();
		foreach($_file as $key=>$value)
			$result[$key] = $value["img"][$index];
		return $result;
	}

And the calling at this function is like this:

	public function do_upload($field = 'userfile', $index = -1)
	{
		// CI code

		if($index > -1)
			$_file = $this->normalizeImageFromArray($_file, $index);
		// Was the file able to be uploaded? If not, determine the reason why.
		if ( ! is_uploaded_file($_file['tmp_name']))
		/*more CI code*/
	}

I don't know if it can work with other types of files. By the moment it works with pdf and images.
