### ISSUE TITLE
compatibility with php 8.2

### ISSUE THREAD

**Issue by ceresaconsultoria** [bcit-ci/CodeIgniter#6194] opened 2023-01-26 13:32 UTC
when will we have 100% compatibility with php 8?

**Comment by svennd** [comment] 2023-01-26 18:06
CI3 is basically in "low" maintenance mode. So never, if you don't submit bugs & patches :+1: It works for 8.0 (end of security : nov '23) and 8.1 (nov '24). I noticed for 8.2 a [bunch of errors ](https://github.com/bcit-ci/CodeIgniter/issues/6192) but that's already a work in progress ;-)

**Comment by gxgpet** [comment] 2023-01-27 01:23
This is more of a duplicate of #6188.

We are compatible with all PHP 8 versions, except PHP 8.2, released less than 2 months ago... 

Did you find any issues other than those appearing on the latest issues/pull requests, here, on GitHub? If yes, please let us know about them.

> CI3 is basically in "low" maintenance mode. So never, if you don't submit bugs & patches 👍 It works for 8.0 (end of security : nov '23) and 8.1 (nov '24). I noticed for 8.2 a [bunch of errors ](https://github.com/bcit-ci/CodeIgniter/issues/6192) but that's already a work in progress ;-)

I don't understand what's the purpose of this sharky comment... If you would have opened the latest issues/PRs here, you would know why we didn't release it yet.

I also find it strange how you managed to find specifically that issue, but not the PR itself that fixes the mentioned issues.

**Closed as completed by gxgpet** 2023-01-27 01:23 UTC

**Comment by bhoupert** [comment] 2024-07-04 11:58
Hello,

Any update for CI 3.1 and PHP 8.2 compatibility ?
