### ISSUE TITLE
Garbage collector does not delete old session data

### ISSUE THREAD

**Issue by osvaldasvalutis** [bcit-ci/CodeIgniter#4866] opened 2016-10-21 08:26 UTC
Hi. I use database storing session data:

```
// CI 3.1.0
$config['sess_driver']				= 'database';
$config['sess_cookie_name']			= 'ci_session';
$config['sess_expiration']			= 3600*12;
$config['sess_save_path']			= 'ci_sessions'; // table name when sess_driver=database
$config['sess_match_ip']			= FALSE;
$config['sess_time_to_update']		= 300;
$config['sess_regenerate_destroy']	= FALSE; // <...> When set to FALSE, the data will be later deleted by the garbage collector.
```

**Problem:** garbage collector does not delete old session data so I have to empty `ci_sessions` table from time to time, otherwise it gets filled with gigabytes of data very fast.

There was no such problem prior to 3.0 version. Any ideas?

**Comment by narfbg** [comment] 2016-10-21 13:34
Duplicate of #4259, this is not a CodeIgniter problem.

Also, we only accept bug reports here. If you need "ideas", please ask for them on our [forums](http://forum.codeigniter.com/) instead.

**Closed by narfbg** 2016-10-21 13:34 UTC
Labels: Duplicate
