### ISSUE TITLE
Controller class names stating with ( i ) capital "I" causes problem on windows

### ISSUE THREAD

**Issue by aydn** [bcit-ci/CodeIgniter#4355] opened 2016-01-03 09:40 UTC
controllers/Index.php

    class Index extends CI_Controller {
    
    	/**
    	 * Index Page for this controller.
    	 *
    	 * Maps to the following URL
    	 * 		http://example.com/index.php/welcome
    	 *	- or -
    	 * 		http://example.com/index.php/welcome/index
    	 *	- or -
    	 * Since this controller is set as the default controller in
    	 * config/routes.php, it's displayed at http://example.com/
    	 *
    	 * So any other public methods not prefixed with an underscore will
    	 * map to /index.php/welcome/<method_name>
    	 * @see http://codeigniter.com/user_guide/general/urls.html
    	 */
    	public function index()
    	{
    		var_dump($this);
    		var_dump('isset: this->config', isset($this->config));
    		
    		print '<br>';
    		var_dump("Why \$this is above not constructed, but below?");
    		print '<br>';
    		
    		parent::__construct();
    		
    		var_dump('isset: this->config', isset($this->config) );
    		var_dump($this);
    		exit("1");
    		
    		$this->load->view('index');
    	}
    }

config/routes.php
 
    $route['default_controller'] = 'index';
    $route['404_override'] = '';
    $route['translate_uri_dashes'] = FALSE;

output

    object(Index)[12]
    string 'isset: this->config' (length=19)
    boolean false
    
    string 'Why $this is above not constructed, but below?' (length=46)
    
    string 'isset: this->config' (length=19)
    boolean true
    object(Index)[12]
      public 'benchmark' => &
        object(CI_Benchmark)[1]
          public 'marker' => 
            array (size=4)
              'total_execution_time_start' => float 1451813830.8452
              'loading_time:_base_classes_start' => float 1451813830.8452
              'loading_time:_base_classes_end' => float 1451813830.8568
              'controller_execution_time_( Index / index )_start' => float 1451813830.8571
      public 'hooks' => &
        object(CI_Hooks)[2]
          public 'enabled' => boolean false
          public 'hooks' => 
            array (size=0)
              empty
          protected '_objects' => 
            array (size=0)
              empty
          protected '_in_progress' => boolean false
      public 'config' => &
        object(CI_Config)[3]
          public 'config' => &
            array (size=48)
              'base_url' => string 'http://www.app.com/' (length=19)
              'index_page' => string '' (length=0)
              'uri_protocol' => string 'REQUEST_URI' (length=11)
              'url_suffix' => string '' (length=0)
              'language' => string 'turkish' (length=7)
              'charset' => string 'UTF-8' (length=5)
              'enable_hooks' => boolean false
              'subclass_prefix' => string 'APP_' (length=4)
              'composer_autoload' => boolean false
              'permitted_uri_chars' => string 'a-z 0-9~%.:_\-' (length=14)
              'allow_get_array' => boolean true
              'enable_query_strings' => boolean false
              'controller_trigger' => string 'c' (length=1)
              'function_trigger' => string 'm' (length=1)
              'directory_trigger' => string 'd' (length=1)
              'log_threshold' => int 1
              'log_path' => string '' (length=0)
              'log_file_extension' => string 'log' (length=3)
              'log_file_permissions' => int 420
              'log_date_format' => string 'Y-m-d H:i:s' (length=11)
              'error_views_path' => string '' (length=0)
              'cache_path' => string '' (length=0)
              'cache_query_string' => boolean false
              'encryption_key' => string 'd2e3370e-07a5-43da-a37f-2a9c2a6fa8d9' (length=36)
              'sess_driver' => string 'files' (length=5)
              'sess_cookie_name' => string 'ssid' (length=4)
              'sess_expiration' => int 0
              'sess_save_path' => null
              'sess_match_ip' => boolean false
              'sess_time_to_update' => int 3600
              'sess_regenerate_destroy' => boolean false
              'cookie_prefix' => string '' (length=0)
              'cookie_domain' => string '.app.com' (length=8)
              'cookie_path' => string '/' (length=1)
              'cookie_secure' => boolean false
              'cookie_httponly' => boolean false
              'standardize_newlines' => boolean false
              'global_xss_filtering' => boolean false
              'csrf_protection' => boolean false
              'csrf_token_name' => string 'csrftoken' (length=9)
              'csrf_cookie_name' => string 'csrfcookie' (length=10)
              'csrf_expire' => int 7200
              'csrf_regenerate' => boolean true
              'csrf_exclude_uris' => 
                array (size=0)
                  ...
              'compress_output' => boolean false
              'time_reference' => string 'Europe/Istanbul' (length=15)
              'rewrite_short_tags' => boolean false
              'proxy_ips' => string '' (length=0)
          public 'is_loaded' => 
            array (size=0)
              empty
          public '_config_paths' => 
            array (size=1)
              0 => string 'C:\wamp\www\app\application\' (length=28)

When I try to run same script with "application/aIndex.php" and default_controller "aIndex" or something else there is no problem.

All files used encoded with UTF-8 without BOM ( original ).

**Comment by afbora** [comment] 2016-01-03 10:22
This is known bug:
https://bugs.php.net/bug.php?id=18556

Solution is setting `LC_CTYPE` as `en_US` like that:

    setlocale(LC_COLLATE, "tr_TR.utf8");
    setlocale(LC_MONETARY, "tr_TR.utf8");
    setlocale(LC_NUMERIC, "tr_TR.utf8");
    setlocale(LC_TIME, "tr_TR.utf8");
    setlocale(LC_MESSAGES, "tr_TR.utf8");
    setlocale(LC_CTYPE, "en_US.utf8");

**Comment by narfbg** [comment] 2016-01-03 10:31
Duplicate of #3451 and [documented](http://www.codeigniter.com/userguide3/general/reserved_names.html).

Nothing to do with locales.

**Closed by narfbg** 2016-01-03 10:31 UTC
