### ISSUE TITLE
Intermittent files session error in CI logs, but not in PHP logs

### ISSUE THREAD

**Issue by Zelfapp** [bcit-ci/CodeIgniter#4657] opened 2016-06-02 00:00 UTC
We're using files for sessions, and running CI 3.0.6.

Several times a day CI logs state CI can't write to "/var/lib/php/session" (see full error below). 

However, in config.php we're actually writing to: "/var/www/vhosts/domain.com/sessions", which works 99% of the time. So the question is why is CI even attempting at all to write to "/var/lib/php/session"? Is this a bug in CI, cookies, or something else on my server? Note: php is not throwing a session write error at all. Only CI is, and there are in fact CI session files from time to time in /var/lib/php/session although there shouldn't be. So php does have write access to this directory.

Thinking somehow the session save path was getting changed to the php.ini default setting for sessions, in system/libraries/Session/drivers/Session_files_driver.php's constructor, I hardcoded the session save path as you can see below, just to test. Even after hardcoding the session save path CI is still attempting to write to /var/lib/php/session, every once in a while. 99% of sessions as I stated are saving in /var/www/vhosts/domain.com/sessions correctly.

![hardcode-session-path](https://cloud.githubusercontent.com/assets/11559805/15729472/4f4faeac-2819-11e6-8db6-4b5e30d28ef9.jpg)

**ERROR - 2016-06-01 14:18:57 --> Severity: Warning --> Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/session) Unknown 0**

**Comment by andersonunsonst** [comment] 2016-06-02 14:09
it's happens to me too

**Comment by narfbg** [comment] 2016-06-02 15:36
Do you have any other relevant logs? This single line is hardly helpful.

This is not caused by CI for sure, but we may be able to work around it.

**Comment by Zelfapp** [comment] 2016-06-02 15:54
That's my point exactly. The session errors that exist only in CI logs are baffling and intermittent. There are no php errors in our server logs, only this error in CI logs.

Unfortunately there is nothing else I can give you. Can you explain how it's possible that CI could even be attempting to write to /var/lib/php/session since I've hardcoded the session save path? Where in the call stack is CI trying to write to my php.ini's default directory? If the answer is, that CI isn't doing that, then I guess it is some issue on my server, but why are there no php error logs and only CI error's about this?

**Comment by narfbg** [comment] 2016-06-02 16:32
I already said that this is **not** caused by CI. It is likely a PHP bug, probably the message itself shows the wrong path.

I have a few ideas for at least what could trigger it, but knowing your PHP version first is better than blind guesswork.

**Comment by Zelfapp** [comment] 2016-06-02 16:52
We're running PHP 5.5.36 php-fpm.

**Comment by andersonunsonst** [comment] 2016-06-02 17:12
5.5.9 here
maybe bug for 5.5 versions ?
 https://bugs.php.net/bug.php?id=69127

**Comment by narfbg** [comment] 2016-06-03 08:47
So, this is triggered when `session_write_close()` is called (can happen automatically or manually) and `CI_Session_files_driver::write()` returns failure. But there's a lot of reasons why it could fail ...

@Zelfapp 

Are you calling `session_write_close()` manually somewhere within your code?
Or perhaps session_start()? (you shouldn't)
Also, can you give us *all* of your session.* INI settings?

And again, do you not have any other session-related logs from requests that trigger this? They may not look related to you, but having this single message with no context is hard to work with.
Set the logging levels to the maximum one.

@andersonunsonst The bug report you've linked has literally nothing to do with this here.

**Comment by Zelfapp** [comment] 2016-06-08 23:11
I'm not calling `session_write_close()` or `session_start()`. I'm using the native CI session library. Unfortunately I don't have any other logs for this. We've checked directory permissions on server, there's no issues there. Not sure what to make of it at this point.

**Comment by narfbg** [comment] 2016-06-09 07:46
Um ... when I say "session-related" logs, I mean absolutely every log message produced by the session library. They may not be directly related to the error, but can give us context at the very least.

Surely, you can't be saying that there are no such logs at all? If unsure, then please assume I need *ALL* logs, regardless of whether they seem important or not.

**Comment by jsieler** [comment] 2016-06-20 10:13
Looks like this with "error log" is somehow related to mine tickets too?!

https://github.com/bcit-ci/CodeIgniter/issues/4667 & https://github.com/bcit-ci/CodeIgniter/issues/4671

**Comment by narfbg** [comment] 2016-06-20 10:37
No, this has nothing to do with your "tickets".
And this is a **bug tracker**, not a support ticket system.

**Comment by narfbg** [comment] 2016-07-27 10:45
Closing due to lack of further feedback.
As previously stated, this is not caused by CI anyway.

**Closed by narfbg** 2016-07-27 10:45 UTC
