### ISSUE TITLE
Table names with commas.

### ISSUE THREAD

**Issue by xmartinj** [bcit-ci/CodeIgniter#2755] opened 2013-12-09 16:39 UTC
Our SQL Server ERP software was installed with a table prefix that includes a comma. CI's Active Record automatically splits the FROM clause based on commas assuming they are separate tables ignoring quotes/brackets to keep the table name together.

i.e. "[Allen,LLC$Customer]" gets changed to "[Allen, LLC$Customer]" which fails.

p.s. The poor choice of table prefix is something we would like to change at the next opportunity, but yet this seems something the FROM function should handle better.

**Comment by xmgcoyi** [comment] 2015-01-21 19:22
MySQL
Database and table names cannot contain “/”, “\”, “.”, or characters that are not permitted in file names.
http://dev.mysql.com/doc/refman/5.0/en/identifiers.html

**Comment by ivantcholakov** [comment] 2015-04-16 06:38
@xmartinj
The closed issue #3764 gives an idea for a workaround. If you pass the selected fields as an array what would happen now?

**Comment by alex7071** [comment] 2017-03-20 08:45
If mysql accepts dots in schema names and fixes bugs related to it, why can't you? https://bugs.mysql.com/bug.php?id=61078 This IS a bug, as you're enforcing something that is not enforced by MySql. Dot names in schema name works fine everywhere else. This is why using third party software sucks.

**Comment by narfbg** [comment] 2017-03-20 11:01
If MySQL can do it, why can't we? Really?

MySQL is a huge project with countless contributors, a powerful corporation behind it, and on top of that only has to deal with itself.  
CodeIgniter is a 3MB framework that sparingly gets small contributions from outsiders, is largely maintained by me alone, in my spare time, and it touches on pretty much all elements of the web technology stack.

Even isolating the issue to databases alone - we try to maintain both compatibility and ease of use between more than 10 database platforms. And the issue isn't even closed yet.

That's why.

**Comment by xmartinj** [comment] 2017-03-20 12:59
No worries. We've moved to Laravel, and are moving away from this database
as well.

**Comment by alex7071** [comment] 2017-03-20 14:05
After 4 years since this has been reported without any attention, anyone can presume this "feature" will never be implemented, even though, it is a bug. Your "holier-than-thou" attitude doesn't do much to convince me you listen to your user-base, so you can abstain from snarky comments. I'm sure you're full of them.

> If MySQL can do it, why can't we? Really?
> 
> MySQL is a huge project with countless contributors, a powerful corporation behind it, and on top of that only has to deal with itself.
> CodeIgniter is a 3MB framework that sparingly gets small contributions from outsiders, is largely maintained by me alone, in my spare time, and it touches on pretty much all elements of the web technology stack.
> 
> Even isolating the issue to databases alone - we try to maintain both compatibility and ease of use between more than 10 database platforms. And the issue isn't even closed yet.
> 
> That's why.

**Comment by xmartinj** [comment] 2017-03-20 14:24
Andrey, are you maintaining primarily for your existing sites that use CI?
What public sites do you have that leverage CI?

**Comment by narfbg** [comment] 2017-03-20 14:39
@alex7071 I suggest you read, then read again your own reply, and repeat that excercise infinitely until you realize that my "holier-than-thou" attitude is a direct response to *yours*.

It's fine if you're unhappy with something, and I don't pretend that CI is perfect or even tries to satisfy everybody's wishes. Just don't act like an entitled brat and then talk about my attitude.

@xmartinj Not that I see how that is related to the issue, but no - I'm not maintaining it primarily for my own projects.

As for your second question - with all due respect, none of your business.

**Comment by flyhait** [comment] 2017-04-12 20:39
its a poor [design](https://www.homeworktiger.com) choice

**Comment by alex7071** [comment] 2017-04-13 06:16
@narfbg uh-huh, i'll get on it and get back to you. Douche.

**Comment by gxgpet** [comment] 2017-04-13 11:57
@alex7071 This is a public space, maybe you should never insult others...?

**Comment by omphemetse** [comment] 2017-10-13 08:30
Why would one decide to include comma's or semicolon's in a table / database name? Isn't this bad practice?

**Comment by alex7071** [comment] 2017-10-13 08:46
@omphemetse How about dots? if i have the databases set up from ages ago with GB of data, like database.prod, database.dev when codeigniter had 0 problems with dots in names and i want to upgrade to a new version i have two options: NOT upgrade, or waste hours and hours of importing data in new databases, changing configs, re-testing the entire application, so i make sure some other dude did not do stupid things like hardcoding names, because of a bad decision that won't be corrected because some dude declares "it's not a bug" or "no time to fix, busy, lulz". I'm not wasting my time fixing it either because it won't ever be merged. Move on to better things seems to be the only sane choice and let this framework die in peace.

**Comment by narfbg** [comment] 2017-10-13 10:37
This issue remains open only as a reminder for us in case some day we want to, and have the time and resources to implement it.

But that being said, everything that could be said here has already been said. I'm locking the conversation. And since that Alex guy is clearly only interested in ranting, he's now one of the few members of our block lists.

**Comment by narfbg** [comment] 2022-01-08 21:20
Ok, let's officially end this ...

For the record, I don't like not having this feature. But attempting to implement it comes with too many potential problems to solve and it's just not happening. All tools come with some limitations and its time we all accepted this limitation.

**Closed by narfbg** 2022-01-08 21:20 UTC
Labels: Feature Request, size: small
