### ISSUE TITLE
idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated

### ISSUE THREAD

**Issue by mayankbha** [bcit-ci/CodeIgniter#5978] opened 2020-08-01 03:41 UTC
Hello,

I am using CodeIgniter version 3.1. I send various type of email via cron scrip that I set on server. Now when cron script runs, I get following message in my email:

A PHP Error was encountered

Severity:    8192
Message:     idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated
Filename:    /home/internm2/public_html/system/libraries/Email.php
Line Number: 1865

Backtrace:
        File: /home/internm2/public_html/application/controllers/Cron.php
        Line: 110
        Function: send

        File: /home/internm2/public_html/index.php
        Line: 315
        Function: require_once

I've checked on net and found that in libraries folder of CodeIgniter, we have Email.php file and in _validate_email_for_shell() function, we are using idn_to_ascii function that causes to this error, I tried many solutions but none is working.

Please suggest me a proper solution to resolve this issue.

Thanks

**Comment by narfbg** [comment] 2021-01-05 11:11
Duplicate of #5300.

**Closed by narfbg** 2021-01-05 11:11 UTC
