### ISSUE TITLE
Form_validation, set_data() -> get_data()

### ISSUE THREAD

**Issue by michesbianan** [bcit-ci/CodeIgniter#4249] opened 2015-11-17 15:50 UTC
The set_data() method of this class is great especially in Thin-Controllers-Fat-Models dev approach. 

With data preppers added in the rules, it will be great if the $validation_data property will also be  reset as with the $POST as in _reset_post_array() method. 

Ultimately, it will be great also to have a method get_data() rather than accessing the public $validation_data property.

**Comment by narfbg** [comment] 2015-11-18 09:23
Duplicate of #2436.

**Closed by narfbg** 2015-11-18 09:23 UTC
Labels: Duplicate
