### ISSUE TITLE
replace_batch() in the query builder

### ISSUE THREAD

**Issue by mehdibo** [bcit-ci/CodeIgniter#5398] opened 2018-01-31 06:20 UTC
A feature request, any chance of adding `replace_batch()` to the query builder?

**Comment by narfbg** [comment] 2018-01-31 20:04
Duplicate of #1652.

Please search for prior issues before opening new ones, and do accompany feature requests with proper motivation for them.

**Closed by narfbg** 2018-01-31 20:04 UTC
