### ISSUE TITLE
input->get_request_header('something'); not working without calling input->request_headers() first

### ISSUE THREAD

**Issue by paranic** [bcit-ci/CodeIgniter#4478] opened 2016-02-22 18:02 UTC
in an non apache environment.

**not working**
```
$this->input->get_request_header('Host');
$this->input->get_request_header('User-Agent');
```

**working**
```
$this->input->request_headers();
$this->input->get_request_header('Host');
$this->input->get_request_header('User-Agent');
```

also i think ```get_request_header()``` is a little slacky written.

**Comment by narfbg** [comment] 2016-02-22 19:46
Duplicate of #4056, which was fixed in 3.0.2.  
The current latest release is 3.0.4 and you should even be testing against dev code before reporting a bug.

**Closed by narfbg** 2016-02-22 19:46 UTC
Labels: Duplicate

**Comment by paranic** [comment] 2016-02-22 20:17
I'm sorry
