### ISSUE TITLE
select data from numeric table name or field 

### ISSUE THREAD

**Issue by synanhero** [bcit-ci/CodeIgniter#4476] opened 2016-02-21 21:33 UTC
for example if i have a table with this name "12332"
this code gives error

       $this->db->from("12332");

but this this one is working nice even it is numeric or string 

       $this->db->from("`$table_name`");

same error happens also numeric field name

**Comment by grigoris86** [comment] 2016-02-22 01:51
stop named table with number! Go to path CodeIgniter/system/database/DB_query_builder.php
and look ci method for from at line 458:





`	public function from($from)
	{
		foreach ((array) $from as $val)
		{
			if (strpos($val, ',') !== FALSE)
			{
				foreach (explode(',', $val) as $v)
				{
					$v = trim($v);
					$this->_track_aliases($v);
					$this->qb_from[] = $v = $this->protect_identifiers($v, TRUE, NULL, FALSE);
					if ($this->qb_caching === TRUE)
					{
						$this->qb_cache_from[] = $v;
						$this->qb_cache_exists[] = 'from';
					}
				}
			}
			else
			{
				$val = trim($val);
				// Extract any aliases that might exist. We use this information
				// in the protect_identifiers to know whether to add a table prefix
				$this->_track_aliases($val);
				$this->qb_from[] = $val = $this->protect_identifiers($val, TRUE, NULL, FALSE);
				if ($this->qb_caching === TRUE)
				{
					$this->qb_cache_from[] = $val;
					$this->qb_cache_exists[] = 'from';
				}
			}
		}
		return $this;
	}`



i think don't have problem with number name of table :)

**Comment by narfbg** [comment] 2016-02-22 15:21
Duplicate of #3877.

@grigoris86 This is not a forum board.

**Closed by narfbg** 2016-02-22 15:21 UTC
