### ISSUE TITLE
_compile_wh adding unnecessary whitespace causing wrong DB queries.

### ISSUE THREAD

**Issue by boonstoppel** [bcit-ci/CodeIgniter#4118] opened 2015-09-15 23:05 UTC
DB queries generated with the method $db->where() that contain the word "and" or "or" are being wrongly parsed in the function _compile_wh. For example this DB query:

$db->select('text');
$db->from('my_table');
$db->where('text', 'black and white or green');
var_dump($db->get()->result_array());
echo $db->last_query();

This will generate:
SELECT `text`
FROM `my_table`
WHERE `text` = 'black and  white or  green'

After the "and" and after the "or" there are now 2 spaces instead of 1.

**Comment by boonstoppel** [comment] 2015-09-15 23:29
Temporary fix for this issue is to not escape the where condition:

$text = 'black and white or green';
$db->where('text', '"' . addslashes($text) . '"', FALSE);

**Comment by narfbg** [comment] 2015-09-16 07:42
Duplicate of #4093.

**Closed by narfbg** 2015-09-16 07:42 UTC
Labels: Duplicate
