### ISSUE TITLE
Codeigniter3 Template parser cannot parse global variable in the loop

### ISSUE THREAD

**Issue by anantapon** [bcit-ci/CodeIgniter#5784] opened 2019-06-22 23:13 UTC
In Codeigniter3 cannot parse variavle {adm_web_root} in the loop, but its work in Codeigniter2 with the same code.

Thank you.
--------------------------------------------------------------
[My code]
Controller:
$data['data_list'] = ! $currency_data ? [] : $currency_data;
$data['adm_web_root'] = 'http://abc.com/';
$this->load->library('parser');
$page_data['page_content'] = $this->parser->parse('man/pagecontent/vw_currency', $data, TRUE);

View:
<table class="table table-striped jambo_table bulk_action">
<thead>
	<tr class="headings">
		<th class="column-title">Code</th>
		<th class="column-title">Currency</th>
		<th class="column-title col-md-3">Actions</th>
	</tr>
</thead>
<tbody>
	{data_list}
	<tr>
		<td>{currency_code}</td>
		<td>{currency_name}</td>
		<td class="col-md-4">
			<div class="btn-group" role="group" aria-label="...">
			  <a href="{adm_web_root}currency?code={currency_code}" class="btn btn-default btn-xs btnEdit"><i class="glyphicon glyphicon-pencil"></i> Edit</a>
			  <a href="{adm_web_root}currency/del?code={currency_code}" class="btn btn-danger btn-xs btnDelete"><i class="glyphicon glyphicon-trash"></i> Delete</a>
			</div>
		</td>
	</tr>
	{/data_list}
</tbody>
</table>

**Comment by narfbg** [comment] 2019-06-23 03:32
Duplicate of #3189.

**Closed by narfbg** 2019-06-23 03:32 UTC
