### ISSUE TITLE
Invalid file type error for CSV or XLSX file upload

### ISSUE THREAD

**Issue by cyberformed** [bcit-ci/CodeIgniter#4589] opened 2016-04-19 11:59 UTC
I am uploading a CSV file using codeigniter 3.  But when I am trying to upload a CSV file it throws invalid file type error in callback function.

`$config['upload_path'] = $upload_dir;

            $config['allowed_types'] = 'csv|xls|xlsx';

            $config['file_name'] = $_FILES['bulk_user_file']['name'] . substr(md5(rand()), 0, 7);

            $config['overwrite'] = true;
            // 5 Mb
            $config['max_size'] = '5242880';
            
            // laod uplaod library
            $this->load->library('upload', $config);`

**Comment by narfbg** [comment] 2016-04-19 12:02
Proper type detection depends on your server environment and is thus outside of CodeIgniter's control; i.e. this is not a bug.

Please post on our [forums](http://forum.codeigniter.com/) if you need help with resolving the issue.

**Closed by narfbg** 2016-04-19 12:02 UTC
