### ISSUE TITLE
xmlrpcs: incoming data urlencoded and int warning

### ISSUE THREAD

**Issue by xenogenesi** [bcit-ci/CodeIgniter#3703] opened 2015-03-25 21:42 UTC
Is xmlrpcs still supposed to work? I'm trying it but having some trouble.

Seems like `$data` given to `xml_parse` is urlencoded, is expected to be so?
As result I get a `Not well-formed (invalid token) at line 1` error.

If I insert a `urldecode` on `xmlrpcs.php` before parsing  `<?xml version="1.0" ?>` become `<?xml_version="1.0" ?>` and give `Space required at line 1`

Also, line 237 of `xmlrpcs.php` with php >= 5.5 give a warning about casting `$parser` to `int` (I guess the same changes with `$pname` in `xmlrpc.php`  are needed)

(I've posted also on CI forum http://forum.codeigniter.com/thread-1494.html but the feedback after post was too fast (no time to read) and no mail arrived yet)

**update**

I was using 3.0rc3, using 2.1.0 work as expected.

**Comment by narfbg** [comment] 2015-03-26 11:03
If you're not sure that something's a bug, post it on the forums. If you're sure that it's a bug - post it here. But don't double post ...

I'm closing this one.

**Closed by narfbg** 2015-03-26 11:03 UTC

**Comment by xenogenesi** [comment] 2015-03-26 11:38
It is a bug, 3.0rc3 doesn't work, 2.1.0 does.

**Comment by narfbg** [comment] 2015-03-26 11:52
Sorry, but "3.0rc3 doesn't work, 2.1.0 does" may mean a thousand things ... You're being really vague here, "seems to be urlencoded" is not a bug report and you're not giving us any other details.

It may very well turn out to be a bug, at which point we'd reopen the issue and work on a fix, but there are hardly any changes in this library between CI2 and CI3, this commit being the only thing that has anything to do with URL-encoding: 20e802eea2fc455622a0f4f721cb82acb046f5b8

You double posted and now you've got a conversation going on in the forums ... figure it out in there and we'll see what to do after.

**Comment by xenogenesi** [comment] 2015-03-26 11:59
This is the shell script I'm using, the `xmlrpc_server` is the common one from [CodeIgniter documentation](https://ellislab.com/codeigniter/user-guide/libraries/xmlrpc.html) under **The Server** chapter.

    #!/bin/sh
    url=http://host/ci-test2/index.php/xmlrpc_server
    data=@-
    cat <<EOF | curl -i -H "Content-Type: text/xml;" -d $data $url
    <?xml version="1.0" ?>
    <methodCall>
      <methodName>Greetings</methodName>
      <params>
        <param>
          <value><string>test string</string></value>
        </param>
      </params>
    </methodCall>
    EOF

**Comment by xenogenesi** [comment] 2015-03-26 13:12
Looks to me like `http_build_query` in the diff you shown me do the *urlencode* and I guess the problem with adding *urldecode* is that there is a question mark `?`, no spaces are allowed on variables name, so the xml become `?xml_version=`.

Using `$data = file_get_contents("php://input");` works but I guess a more *CI* compliant fix is needed.

**Comment by jim-parry** [comment] 2015-03-26 18:34
I have done a bunch of xmlrpc stuff in 2.2; making an example webapp for 3.0 to test this

**Comment by narfbg** [comment] 2015-03-26 19:11
That should do it.

**Comment by xenogenesi** [comment] 2015-03-26 22:39
It work, thank you.

**Comment by jim-parry** [comment] 2015-03-27 22:07
Example, useful I hope: https://github.com/comp4711/example-xmlrpc
