### ISSUE TITLE
Host the latest version of user guides

### ISSUE THREAD

**Issue by zhanghongyi** [bcit-ci/CodeIgniter#4132] opened 2015-09-22 01:17 UTC
I think it would be convenient if we can host a develop version of user guides for references. We keep improving the user guide all the time, but we can only get the latest version by manually compiling it. I can see some advantages of doing auto-generation. First, all the changes to user guides would be validated and posted. For example, considering issue #1825, it's hard to test if it is resolved without an updated user guide online. Second, it is easier for developers to keep up with new changes. 

Originally, I am thinking of making the use of travis-ci. So I submitted a pull request #4128 for validating the generation of documents using travis-ci. But it turned out that it is not the best idea to add complexity to unit testings. So I want to open an discussion thread here for more suggestions.

I would like to suggest something like https://readthedocs.org/, which supports Sphinx(the generation engine we use). And it also supports Github triggers! If this sound like a good thing to do, I will keep looking into it.

**Comment by narfbg** [comment] 2015-09-22 14:44
What is it that makes it so useful to have dev-stage docs online? Seriously, I don't get it.

As for #1825, you don't need to check for it, because the issue is still open, which means it's not fixed.

**Comment by zhanghongyi** [comment] 2015-09-22 16:52
Thanks for the comment @narfbg.

I agree with you that having the latest dev-stage online is *not* a necessary thing to do, but I think it is still a good thing to do. 

For #1825, my point is if we do not have the dev-stage docs online, even after it's fixed, we can not guarantee it is a fix without testing it. What if the fix introduces new bugs?

**Comment by narfbg** [comment] 2015-09-22 17:56
Well, first of all ... it's a feature request, not a bug, so nothing to be "fixed" in there (my bad for not noticing this the first time around).

But either way, "live" builds for something that's mostly static seems excessive to say the least. Changes like #1852, *if* they happen (3 years since that issue has been opened ...), are very, very rare. If preventing a possible bug in the docs interface once in half a year is your only point, it's just not a strong one.
And who says it's not going to be tested in the first place? Sure, more eyes = higher probability to find an presumably existing bug, but still ... having it in public so people can click around and "hopefully" find a bug is not my idea of testing. I'm not convinced that this is what you really want either ... seems to me you just want X.Y.Z-dev version docs easily at your disposal because you use our development code.

To be honest, I don't care that much - if somebody wants to take on that, be my guest. The thing I don't want is our team dedicating time on that, because we're short on resources anyway.

**Comment by zhanghongyi** [comment] 2015-09-22 18:50
Thanks @narfbg. You provided reasonable answers for why we do not have this feature so far. I am now convinced that we need to put more efforts in other fields. 

But here is one more application of my feature request. I think what I proposed is actually the automation of building and deployment for documentations. It can be applied to stable versions as well. In this commit d2985b9a63a9bcb016ff7f8ce7430ec08b468f6a in 3.0 stable branch, we changed a bit about the documents. I am not sure when this will be published to the official online docs. Does it matter? 

Anyway, as you said, we should be focused on high priority things. I may want to pick this up if I have some *spare* time. And I will propose feature request in the forum next time. Is that the right the place for feature request?

**Comment by narfbg** [comment] 2015-09-22 18:57
I ... don't know how to respond to this. The user-guide is not a living document; it is tied to the framework's version. I thought that was quite obvious.

And I don't really understand what kind of a "feature request" you'd be submitting if you would be the one working on it in the first place.

**Comment by jim-parry** [comment] 2015-09-22 21:58
Lemme jump in here :)

If someone is using the develop branch, then they have to build the user guide themselves if they want the most-up-to-date version that incorporates changes since the last release. I have had requests for that, pre-built, including the latest PRs that have been merged. I am guessing this is a convenience.

Before 3.0.0 was released, I effectively did this on the website, updating it weekly or so. You pointed out that the online "official" user guide should really tie-in to the released version, not the in-progress one, so I changed the website accordingly.

Another thing that I did on the website was build & provide an epub version of the in-progress manual. That is on hold, as it is done from the user guide source for sphinx, which is not in the released zip file.

It sounds to me like two things would be beneficial:

1) build multiple targets of the "official" user guide as part of release prep, including html, epub, pdf?; and

2) whenever a PR is incorporated, rebuild the in-progress version of the user guide from the develop branch, and make it accessible either on our website or somewhere else.

I am not sure how the first item would be accomplished ... is there a script you run to make a release? Is this easily done? Or is it more a matter of my building the different versions from the master or the 3.0-stable branch when a new release comes out?

For the second item, I recall some members suggesting a user guide build triggered by a github PR merge ... possibly built outside travis, and then made accessible. I remember that readthedocs.org was mentioned. There appear to be some efforts under way there (https://readthedocs.org/search/?q=codeigniter), but nothing that looks official. Maybe we should put that in place.

My two bits :)

**Comment by narfbg** [comment] 2015-09-23 08:22
It is completely natural that if you're using a dev version of something, you'd have to do some extra work. For example, if we were developing in a compiled language as opposed to an interpreted one, you'd have to always manually compile the whole thing instead of having ready to use binaries.

So, while this may be a convenience for some people, it's also a natural barrier for people trying to do stuff that they are not prepared for, and I believe you'd agree there are too many such people in the CI community. It may sound ... unfriendly, and judge me all you want for this, but I very much like that barrier. Development-stage code just isn't for everybody.

Also, running `make html` isn't a hard task. :)

... which kind of answers the scripts question - there are none. More work is required to update version numbers, remove sources and add only the compiled version to the tag. Once you have Sphinx installed, `make html` is literally the only command you need to run to build the HTML docs.

But when it comes to building live versions, we have another problem - you do have to know which branch you are building from and why. You say build from 'develop', but while develop currently includes new features, it's also very much behind 3.0-stable for bug fixes - they aren't in sync.

**Comment by zhanghongyi** [comment] 2015-09-25 00:44
@jim-parry brought up the topic of adding multiple targets of documentations for the release version. And I just want to add one more bit onto that. I would like to see that we support [Dash](https://kapeli.com/dash) to provide off-line access of documents on Mac platform in the future, because it is a popular(in my opinion) tool on Mac and it has some cool features. Also it does not seem to be a hard thing to achieve as Dash supports sphinx generated documents.

The limitation of Dash is that it only supports Mac...So I just want to bring it up here as a possible candidate of the targets in the future.

**Closed** 2016-02-01 17:00 UTC
Labels: Documentation
