### ISSUE TITLE
DB Query Builder select() and MySQL group_concat() comma separator

### ISSUE THREAD

**Issue by cerealbeer** [bcit-ci/CodeIgniter#4114] opened 2015-09-14 16:31 UTC
Hello,

when doing:

```php
$this->db->select("GROUP_CONCAT(`fruits` SEPARATOR ',') as fruit_list");
```

CI will add a blank space after the defined separator, if this is a **comma**, due to lines [274](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/DB_query_builder.php#L274) and [2282](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/DB_query_builder.php#L2282):

```sql
SELECT GROUP_CONCAT(`fruits` SEPARATOR ', ') as fruit_list ...
```

Returning something like:

```sql
+-------------------------------------+
| fruit_list                          |
+-------------------------------------+
| pineapple, grapes, coconut, oranges |
+-------------------------------------+
```

Instead of:

```sql
+----------------------------------+
| fruit_list                       |
+----------------------------------+
| pineapple,grapes,coconut,oranges |
+----------------------------------+
```

It becomes an issue if redirecting `fruit_list` to the MySQL function `FIND_IN_SET()`, as the query will return results only for the first element in the CSV list and ignore the others.

To avoid the problem at the moment I use `$this->db->query()`.

**Comment by narfbg** [comment] 2015-09-14 21:33
Duplicate of #634.

**Closed by narfbg** 2015-09-14 21:33 UTC
