### ISSUE TITLE
Session Database driver IP address problem 

### ISSUE THREAD

**Issue by maenabbasi** [bcit-ci/CodeIgniter#5539] opened 2018-07-01 18:05 UTC
I am using Codeigniter Session database Driver and hosting my application using cloudflare services, the $config['proxy_ips'] setup correctly and this->input->ip_address()  returns IP correctly, but the IP stored in CI_sessions in the database is the Proxy IP addresses

**Comment by gxgpet** [comment] 2018-07-01 18:10
Duplicate of #4003.

**Closed** 2018-07-22 13:44 UTC
Labels: Duplicate
