### ISSUE TITLE
do_upload() function is broken in xampp

### ISSUE THREAD

**Issue by sabist** [bcit-ci/CodeIgniter#4889] opened 2016-10-30 09:38 UTC
I was using $this->upload->do_upload() in CI 3.1.0 with no problem in xmapp. But now in CI 3.1.1 and 3.1.2 it shows a blank white page with no error on it.
But it working just fine on linux host on the internet. Only in xmapp happend to be broken.

**Comment by gxgpet** [comment] 2016-10-30 10:52
What XAMPP/PHP version are you using?
How are you trying to do the upload/debugging the error? Using the provided example in docs?
This should also include what extension of the file are you uploading.

Providing these will help any investigations go faster. :)

**Comment by sabist** [comment] 2016-10-30 12:02
PHP : 5.6.15
XAMPP : 3.2.2
ENVIRONMENT : development
Extensions allowed : gif, jpg, png, jpeg

and this is the way I am debugging it.
`if (!$this->upload->do_upload('image')) {
    if (ENVIRONMENT === 'development') {
        log_message('error', 'Upload fail.'."\n".__FILE__.' '.__LINE__);
    } else {
        $errors = array('uploading_errors' => $this->upload->display_errors()); 
    }   
}`

I downgraded system files to CI 3.1.0 and it become working again.
I dont think there is any problem with my code because it is working since 3.0.1 till now and no code was changed in this section. It just broke on 3.1.1 and above

**Comment by gxgpet** [comment] 2016-10-30 21:29
I installed XAMPP 3.2.2 on a Windows machine and ran some tests. It appears to be a problem with fileinfo. 

As [this comment](https://github.com/bcit-ci/CodeIgniter/issues/4887#issuecomment-257004923) states, edit your php.ini file and search for `;extension=fileinfo.so` or `;extension=php_fileinfo.dll`, remove the `;`, then restart the Apache module. Is the problem fixed (by using CI 3.1.1 or above)?

**Comment by narfbg** [comment] 2016-10-31 07:42
Duplicate of #4887.

**Closed by narfbg** 2016-10-31 07:42 UTC
Labels: Duplicate
