### ISSUE TITLE
xss_clean

### ISSUE THREAD

**Issue by mfunollet** [bcit-ci/CodeIgniter#5492] opened 2018-05-02 15:38 UTC
We have and issue when apply form validation filter xss_clean.
If the post is for example: ""We are 25% Cat", after pass the filter, the return value is: "We are 25�t".
Only happend with "% c".
Why?

**Comment by maxcreate** [comment] 2018-05-02 23:59
I've just noticed the same issue

**Comment by mfunollet** [comment] 2018-05-03 07:18
But only happend with the letter c '% c'. With another letter works fine

**Comment by narfbg** [comment] 2018-06-01 13:57
Duplicate of #5125.

**Closed by narfbg** 2018-06-01 13:57 UTC
