### ISSUE TITLE
Some errors with active records cache and group_start()

### ISSUE THREAD

**Issue by dahlendesign** [bcit-ci/CodeIgniter#4038] opened 2015-08-08 11:15 UTC
I'm cashing a part of a query, and then runs 3 different get() on the cached part.

First thing I came across was that where_in() didn't calculated the cached where(), and because of this didn't added prefix 'AND'. I solved this by adding a check for cached where() in where_in(), like this:
`$prefix = (count($this->qb_where) === 0 && count($this->qb_cache_where) === 0) ? $this->_group_get_type('') : $this->_group_get_type($type);`
This seems to solve the problem.

The next problem, which I have not been able to solve, is regarding groups in where clause.
I'm using the cache once again (don't know if thats relevant) and adds this:

    $this->db->group_start();
    foreach ($chosen_price_ranges as $i => $value){
        $this->db
            ->or_group_start()
                ->where( array( 'price >=' => $price_range_low[ $value ], 'price <=' => $price_range_high[ $value ] ) )
            ->group_end();
    }
    $this->db->group_end();

This works fine with one loop, and produces:
`AND ( ( `price` >=0 AND `price` <=0 ) )` 

But with two iterations it produces (with a missing end parantes):
`AND ( ( `price` >=0 AND `price` <=0 ) OR ( `price` >= 1 AND `price` <= 10 )`

And with three iterations it produces (with a lot of missing parantes):
`AND ( ( `price` >=0 AND `price` <=0 ) OR ( `price` >= 1 AND `price` <= 10 `price` >= 11 AND `price` <= 30 )`

I found this in group_end():
`'condition' => str_repeat(' ', $this->qb_where_group_count--).')',`
I don't understand why it is adding extra spaces depending on number of open where groups? But it may be irrelevant to this question.

**Comment by narfbg** [comment] 2015-08-10 11:23
The `where_in()` issue was reported in #4012 and fixed in version 3.0.1.
The spaces thing in `group_end()` is just for readability in plain-text (multi-line) format and is indeed irrelevant to whatever issue you're experiencing.

However, I don't quite understand what the problem is with query caching and grouping used together. Your example seems incomplete.

**Comment by narfbg** [comment] 2015-09-14 11:55
Closing due to lack of feedback and overlap with other, already fixed issues.

**Closed by narfbg** 2015-09-14 11:55 UTC
