### ISSUE TITLE
Upload Path doesn't work for Windows Folder (XAMPP Development Environment)

### ISSUE THREAD

**Issue by Corda-zz** [bcit-ci/CodeIgniter#4903] opened 2016-11-07 07:47 UTC
I have upgraded my CodeIgniter from 3.1.0 to 3.1.2 and I got error for Upload Path on Windows. I need to downgrade it to 3.1.0 and Upload Path on Windows works.

I tried 3.1.2 on Linux and it's fine.

Could you fix this problem because I use Windows for development, or maybe you have some tips for me to make it works in 3.1.2 version on Windows?

Thank you.

**Comment by andersonunsonst** [comment] 2016-11-07 10:31
which error ?

**Comment by Corda-zz** [comment] 2016-11-07 10:48
`$config['upload_path']          = './uploads/';`

I made folder 'uploads' on my root folder and I have given full control on that. I tried to upload a file and suddenly get error 500. I already made the environment 'development' and the error still 500. So I confused with this thing.

**Comment by nskarl** [comment] 2016-11-08 06:29
Same problem. But not XAMPP, on live project. Image uploading broken after upgrade to 3.1.2
status 500
statusText "Internal Server Error"

after downgrade to 3.1.0 no problem.

**Comment by toyza55k** [comment] 2016-11-08 07:53
Can you check your "extension=php_fileinfo.dll" in php.ini
Is it enabled?

**Comment by nskarl** [comment] 2016-11-08 08:45
not found extension=php_fileinfo.dll in php.ini

**Comment by narfbg** [comment] 2016-11-08 08:49
Duplicate of #4887.

**Closed by narfbg** 2016-11-08 08:49 UTC
