### ISSUE TITLE
Form validation, set_value() uses $default value when $_POST is empty

### ISSUE THREAD

**Issue by trovster** [bcit-ci/CodeIgniter#3902] opened 2015-06-10 11:24 UTC
Using set_value('field_name', 'default value') on a form field. If you delete the value and submit the form, the form_validation (set to required) correctly flags the field_name, however the value is incorrectly pre-populated with the default value.

Line 446 in system/libraries/Form_validation.php contains the following;

	elseif (isset($validation_array[$field]) && $validation_array[$field] !== '') {
		$this->_field_data[$field]['postdata'] = $validation_array[$field];
	}

This checks the data (defaults to $_POST), however because the data is an empty string, it doesn't populate the postdata. The form_helper function and form_validation method ```set_value()``` reverts back to the default value if the postdata is empty, thus showing the incorrect data in the form.

**Comment by narfbg** [comment] 2015-06-10 11:41
Duplicate of #3816.

**Closed by narfbg** 2015-06-10 11:41 UTC
