### ISSUE TITLE
image_lib class doesn't accept float values for width and height in ci3

### ISSUE THREAD

**Issue by hamzawain7** [bcit-ci/CodeIgniter#5473] opened 2018-04-18 06:09 UTC
so i upgraded from ci2 to ci3 and my cropping code using image_lib broke because i was sending a calculated float value of width and height key to the initialize function which worked fine but now it doesn't. I know giving a float pixel value doesn't makes sense but it worked in 2.1.3 and now it doesn't work in 3.1.7. I think it has to do with the !ctype_digit((string)$val) check in system/libraries/Image_lib.php. If you don't wana accept decimal values thats fine but at least mention it in the code igniter upgrade docs as it is a breaking change.

**Comment by narfbg** [comment] 2018-04-18 09:01
Duplicate of #5113.

**Closed by narfbg** 2018-04-18 09:01 UTC

**Comment by hamzawain7** [comment] 2018-04-18 09:09
please mention this change in the upgrade docs
