### ISSUE TITLE
Form Validation Class with empty rules

### ISSUE THREAD

**Issue by boxsnake** [bcit-ci/CodeIgniter#4588] opened 2016-04-19 07:17 UTC
`Form Validation Class` has something weird.

When there is no rules, it returns **false** when calling `run()` method.
I can not get the point for doing this, because when there is no validation rules, the data should not be validated, and we can assume that is valid.

**Comment by narfbg** [comment] 2016-04-19 07:22
Duplicate of #4210.

**Closed by narfbg** 2016-04-19 07:22 UTC
