### ISSUE TITLE
mktime() expects parameter 1 to be integer, string given

### ISSUE THREAD

**Issue by huglester** [bcit-ci/CodeIgniter#4533] opened 2016-03-14 11:36 UTC
Hello,

this error is triggered from:  helpers/date_helper.php, Line Number: 383.

casting everything to (int) seems to solve the problem.
```php
return mktime(
			(int) substr($time, 8, 2),
			(int) substr($time, 10, 2),
			(int) substr($time, 12, 2),
			(int) substr($time, 4, 2),
			(int) substr($time, 6, 2),
			(int) substr($time, 0, 4)
		);
```

But it appears on php 7.0. Never met this error on PHP 5.3, 5.4, 5.5.

Is this a correct solution? Or problem is somewhere else?

Thank you

**Comment by narfbg** [comment] 2016-03-14 11:38
Duplicate of #4289.

**Closed by narfbg** 2016-03-14 11:38 UTC
Labels: Duplicate
