### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by alexsunnysun** [bcit-ci/CodeIgniter#5119] opened 2017-05-12 02:00 UTC
WHEN I'm request http://localhost:8080/index.php/index/index it's error 404.
Anything else path is ok, like http://localhost:8080/index.php/contact/index

**Comment by jim-parry** [comment] 2017-05-12 03:21
You raised this yesterday, and it was flagged as a duplicate ... Duplicate of #3451.

**Closed by jim-parry** 2017-05-12 03:21 UTC
