### ISSUE TITLE
Only variables should be passed by reference

### ISSUE THREAD

**Issue by milyas77** [bcit-ci/CodeIgniter#5400] opened 2018-02-05 06:47 UTC
i am facing problem 👍  Only variables should be passed by reference in C:\xampp\htdocs\pos\system\codeigniter\core\Common.php on line 148
but i don't know how to fix it 
and line no 148 is :
$objects[$class] =& instantiate_class(new $name());

**Comment by jim-parry** [comment] 2018-02-05 07:14
Duplicate of #5224

**Closed by jim-parry** 2018-02-05 07:14 UTC
