### ISSUE TITLE
Bug in Session_memcached_driver.php - mising Greater-than sign

### ISSUE THREAD

**Issue by MichalSkoula** [bcit-ci/CodeIgniter#5535] opened 2018-06-25 16:44 UTC
file: CodeIgniter-3.1.9/system/libraries/Session/drivers/Session_memcached_driver.php, line 308

there is:

$this->_memcached-get($this->_key_prefix.$id);

there should be:

$this->_memcached->get($this->_key_prefix.$id);

**Comment by gxgpet** [comment] 2018-06-25 16:46
Duplicate of #5526.

**Closed** 2018-06-25 18:12 UTC
Labels: Duplicate
