### ISSUE TITLE
There is a warning when unlink session files "No such file or directory"

### ISSUE THREAD

**Issue by tyl569** [bcit-ci/CodeIgniter#5351] opened 2017-12-06 08:56 UTC
Hi,
I found there is a warning message "unlink(/var/lib/php/session/ci_session398713f044003b888df479c96bd27010820f1053): No such file or directory" in logs. But I check that if there is a session file before executing unlink session files.

![1](https://user-images.githubusercontent.com/8981277/33652924-2ef39394-daa6-11e7-9312-be847c11ca18.png)

Best,
Tyler Teng

**Comment by narfbg** [comment] 2017-12-06 11:27
No such code exists in CodeIgniter.

Note that this is a bug tracker; we don't provide help for code that you write here. Please post your questions on our [forums](https://forum.codeigniter.com/) instead.

Also, post actual code instead of screenshots.

(duplicate of #5350)

**Closed by narfbg** 2017-12-06 11:27 UTC
Labels: Duplicate
