### ISSUE TITLE
CI adds extra space after "and" word in WHERE since 3.0.1

### ISSUE THREAD

**Issue by xorik** [bcit-ci/CodeIgniter#4145] opened 2015-09-28 17:56 UTC
Test code
```
class Test extends CI_Controller
{
	public function index()
	{
		$this->load->database();
		$x = $this->db->where(["test"=>"A and B"])->get_compiled_select("test");
		var_dump($x);
	}
}
```

Result:
```
string(46) "SELECT *
FROM `test`
WHERE `test` = 'A and  B'"
```

**Comment by narfbg** [comment] 2015-09-29 09:10
Duplicate of #4093 ... again; please search for existing issues before opening new ones.

**Closed by narfbg** 2015-09-29 09:10 UTC
Labels: Duplicate
