### ISSUE TITLE
Unable to locate the specified class: Session.php

### ISSUE THREAD

**Issue by songxk** [bcit-ci/CodeIgniter#4464] opened 2016-02-16 07:21 UTC
When i use the hook of CI 3.0.4 it shows this error;
the Hook code 
`
<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
class Authentication extends CI_Controller {

	public function __construct() {
		parent::__construct();
		$this->load->library('session');
	}

	public function auth() {
		$c = $this->router->fetch_class();
		$a = $this->router->fetch_method();
		if($this->_is_ignore($c, $a))
			return true;
		redirect("/permission/login/");
	}
	
	private function _is_ignore($c, $a) {
		$ignore=$this->_get_ignore();
		if (isset($ignore[$c]))  {
			if ($ignore[$c]=="all") {
				return true;
			} else {
				$as = is_array($ignore[$c]) ? $ignore[$c] : array($ignore[$c]);
				return in_array($a, $as);
			}
		}
		return false;
	}

	private function _get_ignore() {
		return array('permission'=>'login', 'user'=>'login');
	}
}
`

the permission controller is 
`
<?php
class Permission extends CI_Controller {
    public function login() {
        echo "hello";
    }
}
`
only these code ....

**Comment by narfbg** [comment] 2016-02-16 09:02
Duplicate of #3921.

Also, 3.0.4 doesn't emit that error message, so you're either reporting the wrong version or you have a `MY_Loader` override, in which case it's your own code that causes it.

**Closed by narfbg** 2016-02-16 09:02 UTC
Labels: Duplicate

**Comment by songxk** [comment] 2016-02-16 20:08
this hook class extends CI_Controller, when call pre_controller  it will create an object of CI_Controller by calling __construct of CI_Controller

then $this->load->library('session');  will call the function '_ci_init_library' of Loader.php，
then the code below of  function _ci_init_library will add the session object to the static variable of the function & is_loaded() in Common.php
`
$this->_ci_classes[$object_name] = $class; 
`


then when finished the pre_controller hook , it will call the method of the controller we write ,
and also execute the function __construct of the CI_Controller ,

`
foreach (is_loaded() as $var => $class)
{
    $this->$var =& load_class($class);
}
`
at this time the result of function 'is_loaded' include the session ，but load_class function did not support the subdir

**Comment by songxk** [comment] 2016-02-16 20:10
just do a more simple test like this:
Hook Code :
`
<?php

class A extends CI_Controller {
    public function __construct() {
        parent::__construct();
        $this->load->library('session');
    }

    public function test() {
        echo 'Hello';
    }
}
`

and Hook Config :

`
<?php
$hook['pre_controller'][]=array(
    'class'    => 'A',
    'function' => 'test',
    'filename' => 'A.php',
    'filepath' => 'hooks'
);
`

**Comment by songxk** [comment] 2016-02-16 20:23
if I don't extends CI_Controller ，at the time pre_controller $ci = &get_instance() will return null , and I can not load library by $ci->load->library....

**Comment by jim-parry** [comment] 2016-02-16 20:31
This is a configuration problem of yours, not a bug. You should raise this on the forum.

**Comment by songxk** [comment] 2016-02-16 23:56
@jim-parry  can you help me to show the error config? i do not know how to solve it

**Comment by jim-parry** [comment] 2016-02-17 00:12
I would be happy to, *on the forum* ... we do not use github for support!

**Comment by songxk** [comment] 2016-02-17 02:06
when register i see "Please tick the checkbox that you see below. This process is used to prevent automated spam bots."  but there is no checkbox .......

**Comment by jim-parry** [comment] 2016-02-17 03:31
Enable javascript. Send further messages to the admin email on the forum, which is me.
